{
    gStyle->SetTitleYOffset(1.7);
    gStyle->SetOptStat(0);
    //gStyle->SetLabelSize(0.025);
    //gStyle->SetTitleSize(0.025);
    
    //Float_t refvalue_cc1pi_mu, refvalue_cc1pi_pi, refvalue_pg_mu, refvalue_pg_pi, refvalue_pg_p, refvalue_pg_e;
    
    Float_t bar_width_sig = 0.2;
    Float_t bar_offset_sig = 0.5 - bar_width_sig*2;
    
    Float_t bar_width_bkg = 0.0625;
    Float_t bar_offset_bkg = 0.5 - bar_width_bkg*6;
    
    // =============== nminus1det variable choice ===============
    
    const char *nminus1detchoices[5] = {"None","FGDs","TPCs","ECal", "SMRD"};
    
    TH1F* nminus1det_musel_mu = new TH1F("nminus1det_musel_mu","#mu^{+} identified as #mu^{+}",5,0,5);
    TH1F* nminus1det_musel_pi = new TH1F("nminus1det_musel_pi","#pi^{+} identified as #mu^{+}",5,0,5);
    TH1F* nminus1det_musel_p = new TH1F("nminus1det_musel_p","p identified as #mu^{+}",5,0,5);
    TH1F* nminus1det_musel_e = new TH1F("nminus1det_musel_e","e^{+} identified as #mu^{+}",5,0,5);
    TH1F* nminus1det_pisel_mu = new TH1F("nminus1det_pisel_mu","#mu^{+} identified as #pi^{+}",5,0,5);
    TH1F* nminus1det_pisel_pi = new TH1F("nminus1det_pisel_pi","#pi^{+} identified as #pi^{+}",5,0,5);
    TH1F* nminus1det_pisel_p = new TH1F("nminus1det_pisel_p","p identified as #pi^{+}",5,0,5);
    TH1F* nminus1det_pisel_e = new TH1F("nminus1det_pisel_e","e^{+} identified as #pi^{+}",5,0,5);
    TH1F* nminus1det_psel_mu = new TH1F("nminus1det_psel_mu","#mu^{+} identified as p",5,0,5);
    TH1F* nminus1det_psel_pi = new TH1F("nminus1det_psel_pi","#pi^{+} identified as p",5,0,5);
    TH1F* nminus1det_psel_p = new TH1F("nminus1det_psel_p","p identified as p",5,0,5);
    TH1F* nminus1det_psel_e = new TH1F("nminus1det_psel_e","e^{+} identified as p",5,0,5);
    TH1F* nminus1det_esel_mu = new TH1F("nminus1det_esel_mu","#mu^{+} identified as e^{+}",5,0,5);
    TH1F* nminus1det_esel_pi = new TH1F("nminus1det_esel_pi","#pi^{+} identified as e^{+}",5,0,5);
    TH1F* nminus1det_esel_p = new TH1F("nminus1det_esel_p","p identified as e^{+}",5,0,5);
    TH1F* nminus1det_esel_e = new TH1F("nminus1det_esel_e","e^{+} identified as e^{+}",5,0,5);
    
    TH1F* nminus1det_musel_mu_diff = new TH1F("nminus1det_musel_mu_diff","#mu^{+} identified as #mu^{+}",5,0,5);
    TH1F* nminus1det_musel_pi_diff = new TH1F("nminus1det_musel_pi_diff","#pi^{+} identified as #mu^{+}",5,0,5);
    TH1F* nminus1det_musel_p_diff = new TH1F("nminus1det_musel_p_diff","p identified as #mu^{+}",5,0,5);
    TH1F* nminus1det_musel_e_diff = new TH1F("nminus1det_musel_e_diff","e^{+} identified as #mu^{+}",5,0,5);
    TH1F* nminus1det_pisel_mu_diff = new TH1F("nminus1det_pisel_mu_diff","#mu^{+} identified as #pi^{+}",5,0,5);
    TH1F* nminus1det_pisel_pi_diff = new TH1F("nminus1det_pisel_pi_diff","#pi^{+} identified as #pi^{+}",5,0,5);
    TH1F* nminus1det_pisel_p_diff = new TH1F("nminus1det_pisel_p_diff","p identified as #pi^{+}",5,0,5);
    TH1F* nminus1det_pisel_e_diff = new TH1F("nminus1det_pisel_e_diff","e^{+} identified as #pi^{+}",5,0,5);
    TH1F* nminus1det_psel_mu_diff = new TH1F("nminus1det_psel_mu_diff","#mu^{+} identified as p",5,0,5);
    TH1F* nminus1det_psel_pi_diff = new TH1F("nminus1det_psel_pi_diff","#pi^{+} identified as p",5,0,5);
    TH1F* nminus1det_psel_p_diff = new TH1F("nminus1det_psel_p_diff","p identified as p",5,0,5);
    TH1F* nminus1det_psel_e_diff = new TH1F("nminus1det_psel_e_diff","e^{+} identified as p",5,0,5);
    TH1F* nminus1det_esel_mu_diff = new TH1F("nminus1det_esel_mu_diff","#mu^{+} identified as e^{+}",5,0,5);
    TH1F* nminus1det_esel_pi_diff = new TH1F("nminus1det_esel_pi_diff","#pi^{+} identified as e^{+}",5,0,5);
    TH1F* nminus1det_esel_p_diff = new TH1F("nminus1det_esel_p_diff","p identified as e^{+}",5,0,5);
    TH1F* nminus1det_esel_e_diff = new TH1F("nminus1det_esel_e_diff","e^{+} identified as e^{+}",5,0,5);
    
    nminus1det_musel_mu->SetFillColor( kBlue);
    nminus1det_musel_pi->SetFillColor( kRed); //nminus1det_musel_pi->SetFillStyle(3305);
    nminus1det_musel_p->SetFillColor( kGreen); //nminus1det_musel_p->SetFillStyle(3305);
    nminus1det_musel_e->SetFillColor( kMagenta); //nminus1det_musel_e->SetFillStyle(3305);
    nminus1det_pisel_mu->SetFillColor( kBlue); //nminus1det_pisel_mu->SetFillStyle(3345);
    nminus1det_pisel_pi->SetFillColor( kRed); 
    nminus1det_pisel_p->SetFillColor( kGreen+1); //nminus1det_pisel_p->SetFillStyle(3345);
    nminus1det_pisel_e->SetFillColor( kMagenta+1); //nminus1det_pisel_e->SetFillStyle(3345);
    nminus1det_psel_mu->SetFillColor( kBlue+1); //nminus1det_psel_mu->SetFillStyle(3354);
    nminus1det_psel_pi->SetFillColor( kRed+1); //nminus1det_psel_pi->SetFillStyle(3354);
    nminus1det_psel_p->SetFillColor( kGreen); 
    nminus1det_psel_e->SetFillColor( kMagenta+2); //nminus1det_psel_e->SetFillStyle(3354);
    nminus1det_esel_mu->SetFillColor( kBlue+2); //nminus1det_esel_mu->SetFillStyle(3144);
    nminus1det_esel_pi->SetFillColor( kRed+2); //nminus1det_esel_pi->SetFillStyle(3144);
    nminus1det_esel_p->SetFillColor( kGreen+2); //nminus1det_esel_p->SetFillStyle(3144);
    nminus1det_esel_e->SetFillColor( kMagenta);
    
    nminus1det_musel_mu_diff->SetFillColor( kBlue);
    nminus1det_musel_pi_diff->SetFillColor( kRed); //nminus1det_musel_pi_diff->SetFillStyle(3305);
    nminus1det_musel_p_diff->SetFillColor( kGreen); //nminus1det_musel_p_diff->SetFillStyle(3305);
    nminus1det_musel_e_diff->SetFillColor( kMagenta); //nminus1det_musel_e_diff->SetFillStyle(3305);
    nminus1det_pisel_mu_diff->SetFillColor( kBlue); //nminus1det_pisel_mu_diff->SetFillStyle(3345);
    nminus1det_pisel_pi_diff->SetFillColor( kRed);
    nminus1det_pisel_p_diff->SetFillColor( kGreen+1); //nminus1det_pisel_p_diff->SetFillStyle(3345);
    nminus1det_pisel_e_diff->SetFillColor( kMagenta+1); //nminus1det_pisel_e_diff->SetFillStyle(3345);
    nminus1det_psel_mu_diff->SetFillColor( kBlue+1); //nminus1det_psel_mu_diff->SetFillStyle(3354);
    nminus1det_psel_pi_diff->SetFillColor( kRed+1); //nminus1det_psel_pi_diff->SetFillStyle(3354);
    nminus1det_psel_p_diff->SetFillColor( kGreen);
    nminus1det_psel_e_diff->SetFillColor( kMagenta+2); //nminus1det_psel_e_diff->SetFillStyle(3354);
    nminus1det_esel_mu_diff->SetFillColor( kBlue+2); //nminus1det_esel_mu_diff->SetFillStyle(3144);
    nminus1det_esel_pi_diff->SetFillColor( kRed+2); //nminus1det_esel_pi->SetFillStyle(3144);
    nminus1det_esel_p_diff->SetFillColor( kGreen+2); //nminus1det_esel_p->SetFillStyle(3144);
    nminus1det_esel_e_diff->SetFillColor( kMagenta);
    
    /*nminus1det_musel_mu->SetBarOffset(bar_offset + (bar_width*0)); nminus1det_musel_mu->SetBarWidth(bar_width);
    nminus1det_musel_pi->SetBarOffset(bar_offset + (bar_width*1)); nminus1det_musel_pi->SetBarWidth(bar_width);
    nminus1det_musel_p->SetBarOffset(bar_offset + (bar_width*2)); nminus1det_musel_p->SetBarWidth(bar_width);
    nminus1det_musel_e->SetBarOffset(bar_offset + (bar_width*3)); nminus1det_musel_e->SetBarWidth(bar_width);
    nminus1det_pisel_mu->SetBarOffset(bar_offset + (bar_width*4)); nminus1det_pisel_mu->SetBarWidth(bar_width);
    nminus1det_pisel_pi->SetBarOffset(bar_offset + (bar_width*5)); nminus1det_pisel_pi->SetBarWidth(bar_width);
    nminus1det_pisel_p->SetBarOffset(bar_offset + (bar_width*6)); nminus1det_pisel_p->SetBarWidth(bar_width);
    nminus1det_pisel_e->SetBarOffset(bar_offset + (bar_width*7)); nminus1det_pisel_e->SetBarWidth(bar_width);
    nminus1det_psel_mu->SetBarOffset(bar_offset + (bar_width*8)); nminus1det_psel_mu->SetBarWidth(bar_width);
    nminus1det_psel_pi->SetBarOffset(bar_offset + (bar_width*9)); nminus1det_psel_pi->SetBarWidth(bar_width);
    nminus1det_psel_p->SetBarOffset(bar_offset + (bar_width*10)); nminus1det_psel_p->SetBarWidth(bar_width);
    nminus1det_psel_e->SetBarOffset(bar_offset + (bar_width*11)); nminus1det_psel_e->SetBarWidth(bar_width);
    nminus1det_esel_mu->SetBarOffset(bar_offset + (bar_width*12)); nminus1det_esel_mu->SetBarWidth(bar_width);
    nminus1det_esel_pi->SetBarOffset(bar_offset + (bar_width*13)); nminus1det_esel_pi->SetBarWidth(bar_width);
    nminus1det_esel_p->SetBarOffset(bar_offset + (bar_width*14)); nminus1det_esel_p->SetBarWidth(bar_width);
    nminus1det_esel_e->SetBarOffset(bar_offset + (bar_width*15)); nminus1det_esel_e->SetBarWidth(bar_width);*/
    
    nminus1det_musel_mu->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); nminus1det_musel_mu->SetBarWidth(bar_width_sig);
    nminus1det_pisel_pi->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); nminus1det_pisel_pi->SetBarWidth(bar_width_sig);
    nminus1det_psel_p->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); nminus1det_psel_p->SetBarWidth(bar_width_sig);
    nminus1det_esel_e->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); nminus1det_esel_e->SetBarWidth(bar_width_sig);
    
    nminus1det_musel_mu_diff->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); nminus1det_musel_mu_diff->SetBarWidth(bar_width_sig);
    nminus1det_pisel_pi_diff->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); nminus1det_pisel_pi_diff->SetBarWidth(bar_width_sig);
    nminus1det_psel_p_diff->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); nminus1det_psel_p_diff->SetBarWidth(bar_width_sig);
    nminus1det_esel_e_diff->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); nminus1det_esel_e_diff->SetBarWidth(bar_width_sig);
    
    nminus1det_pisel_mu->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); nminus1det_pisel_mu->SetBarWidth(bar_width_bkg);
    nminus1det_psel_mu->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); nminus1det_psel_mu->SetBarWidth(bar_width_bkg);
    nminus1det_esel_mu->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); nminus1det_esel_mu->SetBarWidth(bar_width_bkg);
    nminus1det_musel_pi->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); nminus1det_musel_pi->SetBarWidth(bar_width_bkg);
    nminus1det_psel_pi->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); nminus1det_psel_pi->SetBarWidth(bar_width_bkg);
    nminus1det_esel_pi->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); nminus1det_esel_pi->SetBarWidth(bar_width_bkg);
    nminus1det_musel_p->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); nminus1det_musel_p->SetBarWidth(bar_width_bkg);
    nminus1det_pisel_p->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); nminus1det_pisel_p->SetBarWidth(bar_width_bkg);
    nminus1det_esel_p->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); nminus1det_esel_p->SetBarWidth(bar_width_bkg);
    nminus1det_musel_e->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); nminus1det_musel_e->SetBarWidth(bar_width_bkg);
    nminus1det_pisel_e->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); nminus1det_pisel_e->SetBarWidth(bar_width_bkg);
    nminus1det_psel_e->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); nminus1det_psel_e->SetBarWidth(bar_width_bkg);
    
    nminus1det_pisel_mu_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); nminus1det_pisel_mu_diff->SetBarWidth(bar_width_bkg);
    nminus1det_psel_mu_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); nminus1det_psel_mu_diff->SetBarWidth(bar_width_bkg);
    nminus1det_esel_mu_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); nminus1det_esel_mu_diff->SetBarWidth(bar_width_bkg);
    nminus1det_musel_pi_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); nminus1det_musel_pi_diff->SetBarWidth(bar_width_bkg);
    nminus1det_psel_pi_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); nminus1det_psel_pi_diff->SetBarWidth(bar_width_bkg);
    nminus1det_esel_pi_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); nminus1det_esel_pi_diff->SetBarWidth(bar_width_bkg);
    nminus1det_musel_p_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); nminus1det_musel_p_diff->SetBarWidth(bar_width_bkg);
    nminus1det_pisel_p_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); nminus1det_pisel_p_diff->SetBarWidth(bar_width_bkg);
    nminus1det_esel_p_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); nminus1det_esel_p_diff->SetBarWidth(bar_width_bkg);
    nminus1det_musel_e_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); nminus1det_musel_e_diff->SetBarWidth(bar_width_bkg);
    nminus1det_pisel_e_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); nminus1det_pisel_e_diff->SetBarWidth(bar_width_bkg);
    nminus1det_psel_e_diff->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); nminus1det_psel_e_diff->SetBarWidth(bar_width_bkg);
    
    Float_t refvalue_musel_mu = 0.928829;
    Float_t refvalue_musel_pi = 0.321837;
    Float_t refvalue_musel_p = 0.0194994;
    Float_t refvalue_musel_e = 0.0137194;
    Float_t refvalue_pisel_mu = 0.0600165;
    Float_t refvalue_pisel_pi = 0.634636;
    Float_t refvalue_pisel_p = 0.0368206;
    Float_t refvalue_pisel_e = 0.0131849;
    Float_t refvalue_psel_mu = 0.00728658;
    Float_t refvalue_psel_pi = 0.0293201;
    Float_t refvalue_psel_p = 0.898458;
    Float_t refvalue_psel_e = 0.0406682;
    Float_t refvalue_esel_mu = 0.00386783;
    Float_t refvalue_esel_pi = 0.0142065;
    Float_t refvalue_esel_p = 0.045222;
    Float_t refvalue_esel_e = 0.932428;
    
    nminus1det_musel_mu->Fill(nminus1detchoices[0],0.928829);
    nminus1det_musel_pi->Fill(nminus1detchoices[0],0.321837); 
    nminus1det_musel_p->Fill(nminus1detchoices[0],0.0194994);
    nminus1det_musel_e->Fill(nminus1detchoices[0],0.0137194);
    nminus1det_pisel_mu->Fill(nminus1detchoices[0],0.0600165);
    nminus1det_pisel_pi->Fill(nminus1detchoices[0],0.634636);
    nminus1det_pisel_p->Fill(nminus1detchoices[0],0.0368206);
    nminus1det_pisel_e->Fill(nminus1detchoices[0],0.0131849);
    nminus1det_psel_mu->Fill(nminus1detchoices[0],0.00728658);
    nminus1det_psel_pi->Fill(nminus1detchoices[0],0.0293201);
    nminus1det_psel_p->Fill(nminus1detchoices[0],0.898458);
    nminus1det_psel_e->Fill(nminus1detchoices[0],0.0406682);
    nminus1det_esel_mu->Fill(nminus1detchoices[0],0.00386783);
    nminus1det_esel_pi->Fill(nminus1detchoices[0],0.0142065);
    nminus1det_esel_p->Fill(nminus1detchoices[0],0.045222);
    nminus1det_esel_e->Fill(nminus1detchoices[0],0.932428);
    
    nminus1det_musel_mu->Fill(nminus1detchoices[1],0.921876);
    nminus1det_musel_pi->Fill(nminus1detchoices[1],0.328752); 
    nminus1det_musel_p->Fill(nminus1detchoices[1],0.0252558);
    nminus1det_musel_e->Fill(nminus1detchoices[1],0.0163771);
    nminus1det_pisel_mu->Fill(nminus1detchoices[1],0.0639713);
    nminus1det_pisel_pi->Fill(nminus1detchoices[1],0.619626);
    nminus1det_pisel_p->Fill(nminus1detchoices[1],0.0453775);
    nminus1det_pisel_e->Fill(nminus1detchoices[1],0.012784);
    nminus1det_psel_mu->Fill(nminus1detchoices[1],0.0085324);
    nminus1det_psel_pi->Fill(nminus1detchoices[1],0.0313399);
    nminus1det_psel_p->Fill(nminus1detchoices[1],0.854049);
    nminus1det_psel_e->Fill(nminus1detchoices[1],0.0544915);
    nminus1det_esel_mu->Fill(nminus1detchoices[1],0.00562066);
    nminus1det_esel_pi->Fill(nminus1detchoices[1],0.0202828);
    nminus1det_esel_p->Fill(nminus1detchoices[1],0.0753181);
    nminus1det_esel_e->Fill(nminus1detchoices[1],0.916347);
    
    nminus1det_musel_mu->Fill(nminus1detchoices[2],0.941751);
    nminus1det_musel_pi->Fill(nminus1detchoices[2],0.397765); 
    nminus1det_musel_p->Fill(nminus1detchoices[2],0.035455);
    nminus1det_musel_e->Fill(nminus1detchoices[2],0.140148);
    nminus1det_pisel_mu->Fill(nminus1detchoices[2],0.0365343);
    nminus1det_pisel_pi->Fill(nminus1detchoices[2],0.365158);
    nminus1det_pisel_p->Fill(nminus1detchoices[2],0.05065);
    nminus1det_pisel_e->Fill(nminus1detchoices[2],0.117847);
    nminus1det_psel_mu->Fill(nminus1detchoices[2],0.0116614);
    nminus1det_psel_pi->Fill(nminus1detchoices[2],0.104341);
    nminus1det_psel_p->Fill(nminus1detchoices[2],0.88105);
    nminus1det_psel_e->Fill(nminus1detchoices[2],0.0762732);
    nminus1det_esel_mu->Fill(nminus1detchoices[2],0.0100535);
    nminus1det_esel_pi->Fill(nminus1detchoices[2],0.132737);
    nminus1det_esel_p->Fill(nminus1detchoices[2],0.0328447);
    nminus1det_esel_e->Fill(nminus1detchoices[2],0.665731);
    
    nminus1det_musel_mu->Fill(nminus1detchoices[3],0.885964);
    nminus1det_musel_pi->Fill(nminus1detchoices[3],0.526992); 
    nminus1det_musel_p->Fill(nminus1detchoices[3],0.0457924);
    nminus1det_musel_e->Fill(nminus1detchoices[3],0.0225984);
    nminus1det_pisel_mu->Fill(nminus1detchoices[3],0.0906259);
    nminus1det_pisel_pi->Fill(nminus1detchoices[3],0.424928);
    nminus1det_pisel_p->Fill(nminus1detchoices[3],0.0299405);
    nminus1det_pisel_e->Fill(nminus1detchoices[3],0.0111656);
    nminus1det_psel_mu->Fill(nminus1detchoices[3],0.0142979);
    nminus1det_psel_pi->Fill(nminus1detchoices[3],0.0280193);
    nminus1det_psel_p->Fill(nminus1detchoices[3],0.826943);
    nminus1det_psel_e->Fill(nminus1detchoices[3],0.0906607);
    nminus1det_esel_mu->Fill(nminus1detchoices[3],0.00911185);
    nminus1det_esel_pi->Fill(nminus1detchoices[3],0.0200602);
    nminus1det_esel_p->Fill(nminus1detchoices[3],0.097324);
    nminus1det_esel_e->Fill(nminus1detchoices[3],0.875575);
    
    nminus1det_musel_mu->Fill(nminus1detchoices[4],0.920152);
    nminus1det_musel_pi->Fill(nminus1detchoices[4],0.335359); 
    nminus1det_musel_p->Fill(nminus1detchoices[4],0.0203291);
    nminus1det_musel_e->Fill(nminus1detchoices[4],0.0134818);
    nminus1det_pisel_mu->Fill(nminus1detchoices[4],0.0661297);
    nminus1det_pisel_pi->Fill(nminus1detchoices[4],0.62019);
    nminus1det_pisel_p->Fill(nminus1detchoices[4],0.0364403);
    nminus1det_pisel_e->Fill(nminus1detchoices[4],0.0111359);
    nminus1det_psel_mu->Fill(nminus1detchoices[4],0.00931466);
    nminus1det_psel_pi->Fill(nminus1detchoices[4],0.0285499);
    nminus1det_psel_p->Fill(nminus1detchoices[4],0.900705);
    nminus1det_psel_e->Fill(nminus1detchoices[4],0.0464588);
    nminus1det_esel_mu->Fill(nminus1detchoices[4],0.00440382);
    nminus1det_esel_pi->Fill(nminus1detchoices[4],0.0200602);
    nminus1det_esel_p->Fill(nminus1detchoices[4],0.097324);
    nminus1det_esel_e->Fill(nminus1detchoices[4],0.875575);
    
    //TCanvas* canvas_nminus1det_choices = new TCanvas("canvas_nminus1det_choices","",200,10,1000,800);
    TCanvas* canvas_nminus1det_choices_sig = new TCanvas("canvas_nminus1det_choices_sig","",200,10,2000,800);
    canvas_nminus1det_choices_sig->Divide(2,1,0.005,0.005);
    canvas_nminus1det_choices_sig->cd(1);
    nminus1det_musel_mu->GetYaxis()->SetRangeUser(0, 1.0);
    nminus1det_musel_mu->GetXaxis()->SetRangeUser(0, 6);
    nminus1det_musel_mu->GetYaxis()->SetTitle("Efficiency");
    nminus1det_musel_mu->GetYaxis()->SetLabelSize(0.025);
    nminus1det_musel_mu->GetYaxis()->SetTitleSize(0.025);
    nminus1det_musel_mu->GetYaxis()->SetTitleOffset(1.2);
    
    nminus1det_musel_mu->Draw("B");
    nminus1det_pisel_pi->Draw("B same");
    nminus1det_psel_p->Draw("B same");
    nminus1det_esel_e->Draw("B same");
    
    //canvas_nminus1det_choices->BuildLegend();
    //canvas_nminus1det_choices_sig->cd(1)->BuildLegend();
    TLegend *legend_sig = new TLegend(0.55,0.65,0.76,0.82);
    legend_sig->AddEntry(nminus1det_musel_mu,"#mu^{+} identified as #mu^{+}","f");
    legend_sig->AddEntry(nminus1det_pisel_pi,"#pi^{+} identified as #pi^{+}","f");
    legend_sig->AddEntry(nminus1det_psel_p,"p identified as p","f");
    legend_sig->AddEntry(nminus1det_esel_e,"e^{+} identified as e^{+}","f");
    legend_sig->Draw();
    
    //TCanvas* canvas_nminus1det_choices_bkg = new TCanvas("canvas_nminus1det_choices_bkg","",200,10,1000,800);
    TCanvas* canvas_nminus1det_choices_bkg = new TCanvas("canvas_nminus1det_choices_bkg","",200,10,2000,800);
    canvas_nminus1det_choices_bkg->Divide(2,1,0.005,0.005);
    canvas_nminus1det_choices_bkg->cd(1);
    nminus1det_pisel_mu->GetYaxis()->SetRangeUser(0, 1.0);
    nminus1det_pisel_mu->GetXaxis()->SetRangeUser(0, 6);
    nminus1det_pisel_mu->GetYaxis()->SetTitle("Efficiency");
    nminus1det_pisel_mu->GetYaxis()->SetLabelSize(0.025);
    nminus1det_pisel_mu->GetYaxis()->SetTitleSize(0.025);
    nminus1det_pisel_mu->GetYaxis()->SetTitleOffset(1.4);
    
    nminus1det_pisel_mu->Draw("B");
    nminus1det_psel_mu->Draw("B same");
    nminus1det_esel_mu->Draw("B same");
    nminus1det_musel_pi->Draw("B same");
    nminus1det_psel_pi->Draw("B same");
    nminus1det_esel_pi->Draw("B same");
    nminus1det_musel_p->Draw("B same");
    nminus1det_pisel_p->Draw("B same");
    nminus1det_esel_p->Draw("B same");
    nminus1det_musel_e->Draw("B same");
    nminus1det_pisel_e->Draw("B same");
    nminus1det_psel_e->Draw("B same");

    //canvas_nminus1det_choices_bkg->BuildLegend();
    //canvas_nminus1det_choices_bkg->cd(1)->BuildLegend();
    TLegend *legend_bkg = new TLegend(0.55,0.65,0.76,0.82);
    legend_bkg->AddEntry(nminus1det_pisel_mu,"#mu^{+} identified as #pi^{+}","f");
    legend_bkg->AddEntry(nminus1det_psel_mu,"#mu^{+} identified as p","f");
    legend_bkg->AddEntry(nminus1det_esel_mu,"#mu^{+} identified as e^{+}","f");
    legend_bkg->AddEntry(nminus1det_musel_pi,"#pi^{+} identified as #mu^{+}","f");
    legend_bkg->AddEntry(nminus1det_psel_pi,"#pi^{+} identified as p","f");
    legend_bkg->AddEntry(nminus1det_esel_pi,"#pi^{+} identified as e^{+}","f");
    legend_bkg->AddEntry(nminus1det_musel_p,"p identified as #mu^{+}","f");
    legend_bkg->AddEntry(nminus1det_pisel_p,"p identified as #pi^{+}","f");
    legend_bkg->AddEntry(nminus1det_esel_p,"p identified as e^{+}","f");
    legend_bkg->AddEntry(nminus1det_musel_e,"e^{+} identified as #mu^{+}","f");
    legend_bkg->AddEntry(nminus1det_pisel_e,"e^{+} identified as #pi^{+}","f");
    legend_bkg->AddEntry(nminus1det_psel_e,"e^{+} identified as p","f");
    legend_bkg->Draw();
    
    nminus1det_musel_mu_diff->Fill(nminus1detchoices[0], refvalue_musel_mu-nminus1det_musel_mu->GetBinContent(1) );
    nminus1det_musel_pi_diff->Fill(nminus1detchoices[0], refvalue_musel_pi-nminus1det_musel_pi->GetBinContent(1) ); 
    nminus1det_musel_p_diff->Fill(nminus1detchoices[0], refvalue_musel_p-nminus1det_musel_p->GetBinContent(1) );
    nminus1det_musel_e_diff->Fill(nminus1detchoices[0], refvalue_musel_e-nminus1det_musel_e->GetBinContent(1) );
    nminus1det_pisel_mu_diff->Fill(nminus1detchoices[0], refvalue_pisel_mu-nminus1det_pisel_mu->GetBinContent(1) );
    nminus1det_pisel_pi_diff->Fill(nminus1detchoices[0], refvalue_pisel_pi-nminus1det_pisel_pi->GetBinContent(1) );
    nminus1det_pisel_p_diff->Fill(nminus1detchoices[0], refvalue_pisel_p-nminus1det_pisel_p->GetBinContent(1) );
    nminus1det_pisel_e_diff->Fill(nminus1detchoices[0], refvalue_pisel_e-nminus1det_pisel_e->GetBinContent(1) );
    nminus1det_psel_mu_diff->Fill(nminus1detchoices[0], refvalue_psel_mu-nminus1det_psel_mu->GetBinContent(1) );
    nminus1det_psel_pi_diff->Fill(nminus1detchoices[0], refvalue_psel_pi-nminus1det_psel_pi->GetBinContent(1) );
    nminus1det_psel_p_diff->Fill(nminus1detchoices[0], refvalue_psel_p-nminus1det_psel_p->GetBinContent(1) );
    nminus1det_psel_e_diff->Fill(nminus1detchoices[0], refvalue_psel_e-nminus1det_psel_e->GetBinContent(1) );
    nminus1det_esel_mu_diff->Fill(nminus1detchoices[0], refvalue_esel_mu-nminus1det_esel_mu->GetBinContent(1) );
    nminus1det_esel_pi_diff->Fill(nminus1detchoices[0], refvalue_esel_pi-nminus1det_esel_pi->GetBinContent(1) );
    nminus1det_esel_p_diff->Fill(nminus1detchoices[0], refvalue_esel_p-nminus1det_esel_p->GetBinContent(1) );
    nminus1det_esel_e_diff->Fill(nminus1detchoices[0], refvalue_esel_e-nminus1det_esel_e->GetBinContent(1) );
    
    nminus1det_musel_mu_diff->Fill(nminus1detchoices[1], refvalue_musel_mu-nminus1det_musel_mu->GetBinContent(2) );
    nminus1det_musel_pi_diff->Fill(nminus1detchoices[1], refvalue_musel_pi-nminus1det_musel_pi->GetBinContent(2) ); 
    nminus1det_musel_p_diff->Fill(nminus1detchoices[1], refvalue_musel_p-nminus1det_musel_p->GetBinContent(2) );
    nminus1det_musel_e_diff->Fill(nminus1detchoices[1], refvalue_musel_e-nminus1det_musel_e->GetBinContent(2) );
    nminus1det_pisel_mu_diff->Fill(nminus1detchoices[1], refvalue_pisel_mu-nminus1det_pisel_mu->GetBinContent(2) );
    nminus1det_pisel_pi_diff->Fill(nminus1detchoices[1], refvalue_pisel_pi-nminus1det_pisel_pi->GetBinContent(2) );
    nminus1det_pisel_p_diff->Fill(nminus1detchoices[1], refvalue_pisel_p-nminus1det_pisel_p->GetBinContent(2) );
    nminus1det_pisel_e_diff->Fill(nminus1detchoices[1], refvalue_pisel_e-nminus1det_pisel_e->GetBinContent(2)    );
    nminus1det_psel_mu_diff->Fill(nminus1detchoices[1], refvalue_psel_mu-nminus1det_psel_mu->GetBinContent(2) );
    nminus1det_psel_pi_diff->Fill(nminus1detchoices[1], refvalue_psel_pi-nminus1det_psel_pi->GetBinContent(2) );
    nminus1det_psel_p_diff->Fill(nminus1detchoices[1], refvalue_psel_p-nminus1det_psel_p->GetBinContent(2) );
    nminus1det_psel_e_diff->Fill(nminus1detchoices[1], refvalue_psel_e-nminus1det_psel_e->GetBinContent(2) );
    nminus1det_esel_mu_diff->Fill(nminus1detchoices[1], refvalue_esel_mu-nminus1det_esel_mu->GetBinContent(2) );
    nminus1det_esel_pi_diff->Fill(nminus1detchoices[1], refvalue_esel_pi-nminus1det_esel_pi->GetBinContent(2) );
    nminus1det_esel_p_diff->Fill(nminus1detchoices[1], refvalue_esel_p-nminus1det_esel_p->GetBinContent(2) );
    nminus1det_esel_e_diff->Fill(nminus1detchoices[1], refvalue_esel_e-nminus1det_esel_e->GetBinContent(2) );
    
    nminus1det_musel_mu_diff->Fill(nminus1detchoices[2], refvalue_musel_mu-nminus1det_musel_mu->GetBinContent(3) );
    nminus1det_musel_pi_diff->Fill(nminus1detchoices[2], refvalue_musel_pi-nminus1det_musel_pi->GetBinContent(3) ); 
    nminus1det_musel_p_diff->Fill(nminus1detchoices[2], refvalue_musel_p-nminus1det_musel_p->GetBinContent(3) );
    nminus1det_musel_e_diff->Fill(nminus1detchoices[2], refvalue_musel_e-nminus1det_musel_e->GetBinContent(3) );
    nminus1det_pisel_mu_diff->Fill(nminus1detchoices[2], refvalue_pisel_mu-nminus1det_pisel_mu->GetBinContent(3) );
    nminus1det_pisel_pi_diff->Fill(nminus1detchoices[2], refvalue_pisel_pi-nminus1det_pisel_pi->GetBinContent(3) );
    nminus1det_pisel_p_diff->Fill(nminus1detchoices[2], refvalue_pisel_p-nminus1det_pisel_p->GetBinContent(3) );
    nminus1det_pisel_e_diff->Fill(nminus1detchoices[2], refvalue_pisel_e-nminus1det_pisel_e->GetBinContent(3) );
    nminus1det_psel_mu_diff->Fill(nminus1detchoices[2], refvalue_psel_mu-nminus1det_psel_mu->GetBinContent(3) );
    nminus1det_psel_pi_diff->Fill(nminus1detchoices[2], refvalue_psel_pi-nminus1det_psel_pi->GetBinContent(3) );
    nminus1det_psel_p_diff->Fill(nminus1detchoices[2], refvalue_psel_p-nminus1det_psel_p->GetBinContent(3) );
    nminus1det_psel_e_diff->Fill(nminus1detchoices[2], refvalue_psel_e-nminus1det_psel_e->GetBinContent(3) );
    nminus1det_esel_mu_diff->Fill(nminus1detchoices[2], refvalue_esel_mu-nminus1det_esel_mu->GetBinContent(3) );
    nminus1det_esel_pi_diff->Fill(nminus1detchoices[2], refvalue_esel_pi-nminus1det_esel_pi->GetBinContent(3) );
    nminus1det_esel_p_diff->Fill(nminus1detchoices[2], refvalue_esel_p-nminus1det_esel_p->GetBinContent(3) );
    nminus1det_esel_e_diff->Fill(nminus1detchoices[2], refvalue_esel_e-nminus1det_esel_e->GetBinContent(3) );
    
    nminus1det_musel_mu_diff->Fill(nminus1detchoices[3], refvalue_musel_mu-nminus1det_musel_mu->GetBinContent(4) );
    nminus1det_musel_pi_diff->Fill(nminus1detchoices[3], refvalue_musel_pi-nminus1det_musel_pi->GetBinContent(4) ); 
    nminus1det_musel_p_diff->Fill(nminus1detchoices[3], refvalue_musel_p-nminus1det_musel_p->GetBinContent(4) );
    nminus1det_musel_e_diff->Fill(nminus1detchoices[3], refvalue_musel_e-nminus1det_musel_e->GetBinContent(4) );
    nminus1det_pisel_mu_diff->Fill(nminus1detchoices[3], refvalue_pisel_mu-nminus1det_pisel_mu->GetBinContent(4) );
    nminus1det_pisel_pi_diff->Fill(nminus1detchoices[3], refvalue_pisel_pi-nminus1det_pisel_pi->GetBinContent(4) );
    nminus1det_pisel_p_diff->Fill(nminus1detchoices[3], refvalue_pisel_p-nminus1det_pisel_p->GetBinContent(4) );
    nminus1det_pisel_e_diff->Fill(nminus1detchoices[3], refvalue_pisel_e-nminus1det_pisel_e->GetBinContent(4) );
    nminus1det_psel_mu_diff->Fill(nminus1detchoices[3], refvalue_psel_mu-nminus1det_psel_mu->GetBinContent(4) );
    nminus1det_psel_pi_diff->Fill(nminus1detchoices[3], refvalue_psel_pi-nminus1det_psel_pi->GetBinContent(4) );
    nminus1det_psel_p_diff->Fill(nminus1detchoices[3], refvalue_psel_p-nminus1det_psel_p->GetBinContent(4) );
    nminus1det_psel_e_diff->Fill(nminus1detchoices[3], refvalue_psel_e-nminus1det_psel_e->GetBinContent(4) );
    nminus1det_esel_mu_diff->Fill(nminus1detchoices[3], refvalue_esel_mu-nminus1det_esel_mu->GetBinContent(4) );
    nminus1det_esel_pi_diff->Fill(nminus1detchoices[3], refvalue_esel_pi-nminus1det_esel_pi->GetBinContent(4) );
    nminus1det_esel_p_diff->Fill(nminus1detchoices[3], refvalue_esel_p-nminus1det_esel_p->GetBinContent(4) );
    nminus1det_esel_e_diff->Fill(nminus1detchoices[3], refvalue_esel_e-nminus1det_esel_e->GetBinContent(4) );
    
    nminus1det_musel_mu_diff->Fill(nminus1detchoices[4], refvalue_musel_mu-nminus1det_musel_mu->GetBinContent(5) );
    nminus1det_musel_pi_diff->Fill(nminus1detchoices[4], refvalue_musel_pi-nminus1det_musel_pi->GetBinContent(5) ); 
    nminus1det_musel_p_diff->Fill(nminus1detchoices[4], refvalue_musel_p-nminus1det_musel_p->GetBinContent(5) );
    nminus1det_musel_e_diff->Fill(nminus1detchoices[4], refvalue_musel_e-nminus1det_musel_e->GetBinContent(5) );
    nminus1det_pisel_mu_diff->Fill(nminus1detchoices[4], refvalue_pisel_mu-nminus1det_pisel_mu->GetBinContent(5) );
    nminus1det_pisel_pi_diff->Fill(nminus1detchoices[4], refvalue_pisel_pi-nminus1det_pisel_pi->GetBinContent(5) );
    nminus1det_pisel_p_diff->Fill(nminus1detchoices[4], refvalue_pisel_p-nminus1det_pisel_p->GetBinContent(5) );
    nminus1det_pisel_e_diff->Fill(nminus1detchoices[4], refvalue_pisel_e-nminus1det_pisel_e->GetBinContent(5) );
    nminus1det_psel_mu_diff->Fill(nminus1detchoices[4], refvalue_psel_mu-nminus1det_psel_mu->GetBinContent(5) );
    nminus1det_psel_pi_diff->Fill(nminus1detchoices[4], refvalue_psel_pi-nminus1det_psel_pi->GetBinContent(5) );
    nminus1det_psel_p_diff->Fill(nminus1detchoices[4], refvalue_psel_p-nminus1det_psel_p->GetBinContent(5) );
    nminus1det_psel_e_diff->Fill(nminus1detchoices[4], refvalue_psel_e-nminus1det_psel_e->GetBinContent(5) );
    nminus1det_esel_mu_diff->Fill(nminus1detchoices[4], refvalue_esel_mu-nminus1det_esel_mu->GetBinContent(5) );
    nminus1det_esel_pi_diff->Fill(nminus1detchoices[4], refvalue_esel_pi-nminus1det_esel_pi->GetBinContent(5) );
    nminus1det_esel_p_diff->Fill(nminus1detchoices[4], refvalue_esel_p-nminus1det_esel_p->GetBinContent(5) );
    nminus1det_esel_e_diff->Fill(nminus1detchoices[4], refvalue_esel_e-nminus1det_esel_e->GetBinContent(5) );
    
    //TCanvas* canvas_nminus1det_choices_diff = new TCanvas("canvas_nminus1det_choices_diff","",200,10,1000,800);
    canvas_nminus1det_choices_sig->cd(2);
    nminus1det_musel_mu_diff->GetYaxis()->SetRangeUser(-0.2, 0.2);
    nminus1det_musel_mu_diff->GetXaxis()->SetRangeUser(1, 5);
    nminus1det_musel_mu_diff->GetYaxis()->SetTitle("Difference in efficiency (all subdetectors - subdetector removed)");
    nminus1det_musel_mu_diff->GetYaxis()->SetLabelSize(0.025);
    nminus1det_musel_mu_diff->GetYaxis()->SetTitleSize(0.025);
    nminus1det_musel_mu_diff->GetYaxis()->SetTitleOffset(1.6);
    
    nminus1det_musel_mu_diff->Draw("B");
    nminus1det_pisel_pi_diff->Draw("B same");
    nminus1det_psel_p_diff->Draw("B same");
    nminus1det_esel_e_diff->Draw("B same");
    
    //canvas_nminus1det_choices_diff->BuildLegend();
    
    //TCanvas* canvas_nminus1det_choices_bkg_diff = new TCanvas("canvas_nminus1det_choices_bkg_diff","",200,10,1000,800);
    canvas_nminus1det_choices_bkg->cd(2);
    nminus1det_pisel_mu_diff->GetYaxis()->SetRangeUser(-0.2, 0.2);
    nminus1det_pisel_mu_diff->GetXaxis()->SetRangeUser(1, 5);
    nminus1det_pisel_mu_diff->GetYaxis()->SetTitle("Difference in efficiency (all subdetectors - subdetector removed)");
    nminus1det_pisel_mu_diff->GetYaxis()->SetLabelSize(0.025);
    nminus1det_pisel_mu_diff->GetYaxis()->SetTitleSize(0.025);
    nminus1det_pisel_mu_diff->GetYaxis()->SetTitleOffset(1.5);
    
    nminus1det_pisel_mu_diff->Draw("B");
    nminus1det_psel_mu_diff->Draw("B same");
    nminus1det_esel_mu_diff->Draw("B same");
    nminus1det_musel_pi_diff->Draw("B same");
    nminus1det_psel_pi_diff->Draw("B same");
    nminus1det_esel_pi_diff->Draw("B same");
    nminus1det_musel_p_diff->Draw("B same");
    nminus1det_pisel_p_diff->Draw("B same");
    nminus1det_esel_p_diff->Draw("B same");
    nminus1det_musel_e_diff->Draw("B same");
    nminus1det_pisel_e_diff->Draw("B same");
    nminus1det_psel_e_diff->Draw("B same");
    
    //canvas_nminus1det_choices_bkg_diff->BuildLegend();

}
