{
    gStyle->SetTitleYOffset(1.7);
    gStyle->SetOptStat(0);
    //gStyle->SetLabelSize(0.025);
    //gStyle->SetTitleSize(0.025);
    
    //Float_t refvalue_cc1pi_mu, refvalue_cc1pi_pi, refvalue_pg_mu, refvalue_pg_pi, refvalue_pg_p, refvalue_pg_e;
    
    Float_t bar_width_sig = 0.2;
    Float_t bar_offset_sig = 0.5 - bar_width_sig*2;
    
    Float_t bar_width_bkg = 0.0625;
    Float_t bar_offset_bkg = 0.5 - bar_width_bkg*6;
    
    // =============== TPC2 variable choice ===============
    
    const char *tpc2varchoices[3] = {"TPC2 dE/dx","TPC2 pulls","TPC2 likelihoods"};
    
    TH1F* TPC2_musel_mu1 = new TH1F("TPC2_musel_mu1","#mu^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_pi1 = new TH1F("TPC2_musel_pi1","#pi^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_p1 = new TH1F("TPC2_musel_p1","p identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_e1 = new TH1F("TPC2_musel_e1","e^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_pisel_mu1 = new TH1F("TPC2_pisel_mu1","#mu^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_pi1 = new TH1F("TPC2_pisel_pi1","#pi^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_p1 = new TH1F("TPC2_pisel_p1","p identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_e1 = new TH1F("TPC2_pisel_e1","e^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_psel_mu1 = new TH1F("TPC2_psel_mu1","#mu^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_pi1 = new TH1F("TPC2_psel_pi1","#pi^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_p1 = new TH1F("TPC2_psel_p1","p identified as p",3,0,3);
    TH1F* TPC2_psel_e1 = new TH1F("TPC2_psel_e1","e^{+} identified as p",3,0,3);
    TH1F* TPC2_esel_mu1 = new TH1F("TPC2_esel_mu1","#mu^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_pi1 = new TH1F("TPC2_esel_pi1","#pi^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_p1 = new TH1F("TPC2_esel_p1","p identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_e1 = new TH1F("TPC2_esel_e1","e^{+} identified as e^{+}",3,0,3);
  
    TH1F* TPC2_musel_mu2 = new TH1F("TPC2_musel_mu2","#mu^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_pi2 = new TH1F("TPC2_musel_pi2","#pi^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_p2 = new TH1F("TPC2_musel_p2","p identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_e2 = new TH1F("TPC2_musel_e2","e^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_pisel_mu2 = new TH1F("TPC2_pisel_mu2","#mu^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_pi2 = new TH1F("TPC2_pisel_pi2","#pi^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_p2 = new TH1F("TPC2_pisel_p2","p identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_e2 = new TH1F("TPC2_pisel_e2","e^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_psel_mu2 = new TH1F("TPC2_psel_mu2","#mu^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_pi2 = new TH1F("TPC2_psel_pi2","#pi^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_p2 = new TH1F("TPC2_psel_p2","p identified as p",3,0,3);
    TH1F* TPC2_psel_e2 = new TH1F("TPC2_psel_e2","e^{+} identified as p",3,0,3);
    TH1F* TPC2_esel_mu2 = new TH1F("TPC2_esel_mu2","#mu^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_pi2 = new TH1F("TPC2_esel_pi2","#pi^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_p2 = new TH1F("TPC2_esel_p2","p identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_e2 = new TH1F("TPC2_esel_e2","e^{+} identified as e^{+}",3,0,3);
    
    TH1F* TPC2_musel_mu_diff1 = new TH1F("TPC2_musel_mu_diff1","#mu^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_pi_diff1 = new TH1F("TPC2_musel_pi_diff1","#pi^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_p_diff1 = new TH1F("TPC2_musel_p_diff1","p identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_e_diff1 = new TH1F("TPC2_musel_e_diff1","e^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_pisel_mu_diff1 = new TH1F("TPC2_pisel_mu_diff1","#mu^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_pi_diff1 = new TH1F("TPC2_pisel_pi_diff1","#pi^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_p_diff1 = new TH1F("TPC2_pisel_p_diff1","p identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_e_diff1 = new TH1F("TPC2_pisel_e_diff1","e^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_psel_mu_diff1 = new TH1F("TPC2_psel_mu_diff1","#mu^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_pi_diff1 = new TH1F("TPC2_psel_pi_diff1","#pi^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_p_diff1 = new TH1F("TPC2_psel_p_diff1","p identified as p",3,0,3);
    TH1F* TPC2_psel_e_diff1 = new TH1F("TPC2_psel_e_diff1","e^{+} identified as p",3,0,3);
    TH1F* TPC2_esel_mu_diff1 = new TH1F("TPC2_esel_mu_diff1","#mu^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_pi_diff1 = new TH1F("TPC2_esel_pi_diff1","#pi^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_p_diff1 = new TH1F("TPC2_esel_p_diff1","p identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_e_diff1 = new TH1F("TPC2_esel_e_diff1","e^{+} identified as e^{+}",3,0,3);
  
    TH1F* TPC2_musel_mu_diff2 = new TH1F("TPC2_musel_mu_diff2","#mu^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_pi_diff2 = new TH1F("TPC2_musel_pi_diff2","#pi^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_p_diff2 = new TH1F("TPC2_musel_p_diff2","p identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_e_diff2 = new TH1F("TPC2_musel_e_diff2","e^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_pisel_mu_diff2 = new TH1F("TPC2_pisel_mu_diff2","#mu^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_pi_diff2 = new TH1F("TPC2_pisel_pi_diff2","#pi^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_p_diff2 = new TH1F("TPC2_pisel_p_diff2","p identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_e_diff2 = new TH1F("TPC2_pisel_e_diff2","e^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_psel_mu_diff2 = new TH1F("TPC2_psel_mu_diff2","#mu^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_pi_diff2 = new TH1F("TPC2_psel_pi_diff2","#pi^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_p_diff2 = new TH1F("TPC2_psel_p_diff2","p identified as p",3,0,3);
    TH1F* TPC2_psel_e_diff2 = new TH1F("TPC2_psel_e_diff2","e^{+} identified as p",3,0,3);
    TH1F* TPC2_esel_mu_diff2 = new TH1F("TPC2_esel_mu_diff2","#mu^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_pi_diff2 = new TH1F("TPC2_esel_pi_diff2","#pi^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_p_diff2 = new TH1F("TPC2_esel_p_diff2","p identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_e_diff2 = new TH1F("TPC2_esel_e_diff2","e^{+} identified as e^{+}",3,0,3);
    
    TPC2_musel_mu1->SetFillColor( kBlue);
    TPC2_musel_pi1->SetFillColor( kRed);
    TPC2_musel_p1->SetFillColor( kGreen);
    TPC2_musel_e1->SetFillColor( kMagenta);
    TPC2_pisel_mu1->SetFillColor( kBlue);
    TPC2_pisel_pi1->SetFillColor( kRed); 
    TPC2_pisel_p1->SetFillColor( kGreen+1);
    TPC2_pisel_e1->SetFillColor( kMagenta+1);
    TPC2_psel_mu1->SetFillColor( kBlue+1);
    TPC2_psel_pi1->SetFillColor( kRed+1);
    TPC2_psel_p1->SetFillColor( kGreen); 
    TPC2_psel_e1->SetFillColor( kMagenta+2);
    TPC2_esel_mu1->SetFillColor( kBlue+2);
    TPC2_esel_pi1->SetFillColor( kRed+2);
    TPC2_esel_p1->SetFillColor( kGreen+2);
    TPC2_esel_e1->SetFillColor( kMagenta);
    
    TPC2_musel_mu_diff1->SetFillColor( kBlue);
    TPC2_musel_pi_diff1->SetFillColor( kRed);
    TPC2_musel_p_diff1->SetFillColor( kGreen);
    TPC2_musel_e_diff1->SetFillColor( kMagenta);
    TPC2_pisel_mu_diff1->SetFillColor( kBlue);
    TPC2_pisel_pi_diff1->SetFillColor( kRed);
    TPC2_pisel_p_diff1->SetFillColor( kGreen+1);
    TPC2_pisel_e_diff1->SetFillColor( kMagenta+1);
    TPC2_psel_mu_diff1->SetFillColor( kBlue+1);
    TPC2_psel_pi_diff1->SetFillColor( kRed+1);
    TPC2_psel_p_diff1->SetFillColor( kGreen);
    TPC2_psel_e_diff1->SetFillColor( kMagenta+2);
    TPC2_esel_mu_diff1->SetFillColor( kBlue+2);
    TPC2_esel_pi_diff1->SetFillColor( kRed+2);
    TPC2_esel_p_diff1->SetFillColor( kGreen+2);
    TPC2_esel_e_diff1->SetFillColor( kMagenta);
    
    TPC2_musel_mu1->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); TPC2_musel_mu1->SetBarWidth(bar_width_sig);
    TPC2_pisel_pi1->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); TPC2_pisel_pi1->SetBarWidth(bar_width_sig);
    TPC2_psel_p1->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); TPC2_psel_p1->SetBarWidth(bar_width_sig);
    TPC2_esel_e1->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); TPC2_esel_e1->SetBarWidth(bar_width_sig);
    
    TPC2_musel_mu_diff1->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); TPC2_musel_mu_diff1->SetBarWidth(bar_width_sig);
    TPC2_pisel_pi_diff1->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); TPC2_pisel_pi_diff1->SetBarWidth(bar_width_sig);
    TPC2_psel_p_diff1->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); TPC2_psel_p_diff1->SetBarWidth(bar_width_sig);
    TPC2_esel_e_diff1->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); TPC2_esel_e_diff1->SetBarWidth(bar_width_sig);
    
    TPC2_pisel_mu1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); TPC2_pisel_mu1->SetBarWidth(bar_width_bkg);
    TPC2_psel_mu1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); TPC2_psel_mu1->SetBarWidth(bar_width_bkg);
    TPC2_esel_mu1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); TPC2_esel_mu1->SetBarWidth(bar_width_bkg);
    TPC2_musel_pi1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); TPC2_musel_pi1->SetBarWidth(bar_width_bkg);
    TPC2_psel_pi1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); TPC2_psel_pi1->SetBarWidth(bar_width_bkg);
    TPC2_esel_pi1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); TPC2_esel_pi1->SetBarWidth(bar_width_bkg);
    TPC2_musel_p1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); TPC2_musel_p1->SetBarWidth(bar_width_bkg);
    TPC2_pisel_p1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); TPC2_pisel_p1->SetBarWidth(bar_width_bkg);
    TPC2_esel_p1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); TPC2_esel_p1->SetBarWidth(bar_width_bkg);
    TPC2_musel_e1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); TPC2_musel_e1->SetBarWidth(bar_width_bkg);
    TPC2_pisel_e1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); TPC2_pisel_e1->SetBarWidth(bar_width_bkg);
    TPC2_psel_e1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); TPC2_psel_e1->SetBarWidth(bar_width_bkg);
    
    TPC2_pisel_mu_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); TPC2_pisel_mu_diff1->SetBarWidth(bar_width_bkg);
    TPC2_psel_mu_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); TPC2_psel_mu_diff1->SetBarWidth(bar_width_bkg);
    TPC2_esel_mu_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); TPC2_esel_mu_diff1->SetBarWidth(bar_width_bkg);
    TPC2_musel_pi_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); TPC2_musel_pi_diff1->SetBarWidth(bar_width_bkg);
    TPC2_psel_pi_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); TPC2_psel_pi_diff1->SetBarWidth(bar_width_bkg);
    TPC2_esel_pi_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); TPC2_esel_pi_diff1->SetBarWidth(bar_width_bkg);
    TPC2_musel_p_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); TPC2_musel_p_diff1->SetBarWidth(bar_width_bkg);
    TPC2_pisel_p_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); TPC2_pisel_p_diff1->SetBarWidth(bar_width_bkg);
    TPC2_esel_p_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); TPC2_esel_p_diff1->SetBarWidth(bar_width_bkg);
    TPC2_musel_e_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); TPC2_musel_e_diff1->SetBarWidth(bar_width_bkg);
    TPC2_pisel_e_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); TPC2_pisel_e_diff1->SetBarWidth(bar_width_bkg);
    TPC2_psel_e_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); TPC2_psel_e_diff1->SetBarWidth(bar_width_bkg);
  
    TPC2_musel_mu2->SetFillColor( kBlue);
    TPC2_musel_pi2->SetFillColor( kRed);
    TPC2_musel_p2->SetFillColor( kGreen);
    TPC2_musel_e2->SetFillColor( kMagenta);
    TPC2_pisel_mu2->SetFillColor( kBlue);
    TPC2_pisel_pi2->SetFillColor( kRed); 
    TPC2_pisel_p2->SetFillColor( kGreen+1);
    TPC2_pisel_e2->SetFillColor( kMagenta+1);
    TPC2_psel_mu2->SetFillColor( kBlue+1);
    TPC2_psel_pi2->SetFillColor( kRed+1);
    TPC2_psel_p2->SetFillColor( kGreen); 
    TPC2_psel_e2->SetFillColor( kMagenta+2);
    TPC2_esel_mu2->SetFillColor( kBlue+2);
    TPC2_esel_pi2->SetFillColor( kRed+2);
    TPC2_esel_p2->SetFillColor( kGreen+2);
    TPC2_esel_e2->SetFillColor( kMagenta);
    
    TPC2_musel_mu_diff2->SetFillColor( kBlue);
    TPC2_musel_pi_diff2->SetFillColor( kRed);
    TPC2_musel_p_diff2->SetFillColor( kGreen);
    TPC2_musel_e_diff2->SetFillColor( kMagenta);
    TPC2_pisel_mu_diff2->SetFillColor( kBlue);
    TPC2_pisel_pi_diff2->SetFillColor( kRed);
    TPC2_pisel_p_diff2->SetFillColor( kGreen+1);
    TPC2_pisel_e_diff2->SetFillColor( kMagenta+1);
    TPC2_psel_mu_diff2->SetFillColor( kBlue+1);
    TPC2_psel_pi_diff2->SetFillColor( kRed+1);
    TPC2_psel_p_diff2->SetFillColor( kGreen);
    TPC2_psel_e_diff2->SetFillColor( kMagenta+2);
    TPC2_esel_mu_diff2->SetFillColor( kBlue+2);
    TPC2_esel_pi_diff2->SetFillColor( kRed+2);
    TPC2_esel_p_diff2->SetFillColor( kGreen+2);
    TPC2_esel_e_diff2->SetFillColor( kMagenta);
    
    TPC2_musel_mu2->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); TPC2_musel_mu2->SetBarWidth(bar_width_sig);
    TPC2_pisel_pi2->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); TPC2_pisel_pi2->SetBarWidth(bar_width_sig);
    TPC2_psel_p2->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); TPC2_psel_p2->SetBarWidth(bar_width_sig);
    TPC2_esel_e2->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); TPC2_esel_e2->SetBarWidth(bar_width_sig);
    
    TPC2_musel_mu_diff2->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); TPC2_musel_mu_diff2->SetBarWidth(bar_width_sig);
    TPC2_pisel_pi_diff2->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); TPC2_pisel_pi_diff2->SetBarWidth(bar_width_sig);
    TPC2_psel_p_diff2->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); TPC2_psel_p_diff2->SetBarWidth(bar_width_sig);
    TPC2_esel_e_diff2->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); TPC2_esel_e_diff2->SetBarWidth(bar_width_sig);
    
    TPC2_pisel_mu2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); TPC2_pisel_mu2->SetBarWidth(bar_width_bkg);
    TPC2_psel_mu2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); TPC2_psel_mu2->SetBarWidth(bar_width_bkg);
    TPC2_esel_mu2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); TPC2_esel_mu2->SetBarWidth(bar_width_bkg);
    TPC2_musel_pi2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); TPC2_musel_pi2->SetBarWidth(bar_width_bkg);
    TPC2_psel_pi2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); TPC2_psel_pi2->SetBarWidth(bar_width_bkg);
    TPC2_esel_pi2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); TPC2_esel_pi2->SetBarWidth(bar_width_bkg);
    TPC2_musel_p2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); TPC2_musel_p2->SetBarWidth(bar_width_bkg);
    TPC2_pisel_p2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); TPC2_pisel_p2->SetBarWidth(bar_width_bkg);
    TPC2_esel_p2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); TPC2_esel_p2->SetBarWidth(bar_width_bkg);
    TPC2_musel_e2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); TPC2_musel_e2->SetBarWidth(bar_width_bkg);
    TPC2_pisel_e2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); TPC2_pisel_e2->SetBarWidth(bar_width_bkg);
    TPC2_psel_e2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); TPC2_psel_e2->SetBarWidth(bar_width_bkg);
    
    TPC2_pisel_mu_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); TPC2_pisel_mu_diff2->SetBarWidth(bar_width_bkg);
    TPC2_psel_mu_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); TPC2_psel_mu_diff2->SetBarWidth(bar_width_bkg);
    TPC2_esel_mu_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); TPC2_esel_mu_diff2->SetBarWidth(bar_width_bkg);
    TPC2_musel_pi_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); TPC2_musel_pi_diff2->SetBarWidth(bar_width_bkg);
    TPC2_psel_pi_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); TPC2_psel_pi_diff2->SetBarWidth(bar_width_bkg);
    TPC2_esel_pi_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); TPC2_esel_pi_diff2->SetBarWidth(bar_width_bkg);
    TPC2_musel_p_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); TPC2_musel_p_diff2->SetBarWidth(bar_width_bkg);
    TPC2_pisel_p_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); TPC2_pisel_p_diff2->SetBarWidth(bar_width_bkg);
    TPC2_esel_p_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); TPC2_esel_p_diff2->SetBarWidth(bar_width_bkg);
    TPC2_musel_e_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); TPC2_musel_e_diff2->SetBarWidth(bar_width_bkg);
    TPC2_pisel_e_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); TPC2_pisel_e_diff2->SetBarWidth(bar_width_bkg);
    TPC2_psel_e_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); TPC2_psel_e_diff2->SetBarWidth(bar_width_bkg);
    
    TPC2_musel_mu1->Fill(tpc2varchoices[0],0.);
    TPC2_musel_pi1->Fill(tpc2varchoices[0],0.); 
    TPC2_musel_p1->Fill(tpc2varchoices[0],0.);
    TPC2_musel_e1->Fill(tpc2varchoices[0],0.);
    TPC2_pisel_mu1->Fill(tpc2varchoices[0],0.);
    TPC2_pisel_pi1->Fill(tpc2varchoices[0],0.);
    TPC2_pisel_p1->Fill(tpc2varchoices[0],0.);
    TPC2_pisel_e1->Fill(tpc2varchoices[0],0.);
    TPC2_psel_mu1->Fill(tpc2varchoices[0],0.);
    TPC2_psel_pi1->Fill(tpc2varchoices[0],0.);
    TPC2_psel_p1->Fill(tpc2varchoices[0],0.);
    TPC2_psel_e1->Fill(tpc2varchoices[0],0.);
    TPC2_esel_mu1->Fill(tpc2varchoices[0],0.);
    TPC2_esel_pi1->Fill(tpc2varchoices[0],0.);
    TPC2_esel_p1->Fill(tpc2varchoices[0],0.);
    TPC2_esel_e1->Fill(tpc2varchoices[0],0.);
    
    TPC2_musel_mu1->Fill(tpc2varchoices[1],0.);
    TPC2_musel_pi1->Fill(tpc2varchoices[1],0.); 
    TPC2_musel_p1->Fill(tpc2varchoices[1],0.);
    TPC2_musel_e1->Fill(tpc2varchoices[1],0.);
    TPC2_pisel_mu1->Fill(tpc2varchoices[1],0.);
    TPC2_pisel_pi1->Fill(tpc2varchoices[1],0.);
    TPC2_pisel_p1->Fill(tpc2varchoices[1],0.);
    TPC2_pisel_e1->Fill(tpc2varchoices[1],0.);
    TPC2_psel_mu1->Fill(tpc2varchoices[1],0.);
    TPC2_psel_pi1->Fill(tpc2varchoices[1],0.);
    TPC2_psel_p1->Fill(tpc2varchoices[1],0.);
    TPC2_psel_e1->Fill(tpc2varchoices[1],0.);
    TPC2_esel_mu1->Fill(tpc2varchoices[1],0.);
    TPC2_esel_pi1->Fill(tpc2varchoices[1],0.);
    TPC2_esel_p1->Fill(tpc2varchoices[1],0.);
    TPC2_esel_e1->Fill(tpc2varchoices[1],0.);
    
    TPC2_musel_mu1->Fill(tpc2varchoices[2],0.);
    TPC2_musel_pi1->Fill(tpc2varchoices[2],0.); 
    TPC2_musel_p1->Fill(tpc2varchoices[2],0.);
    TPC2_musel_e1->Fill(tpc2varchoices[2],0.);
    TPC2_pisel_mu1->Fill(tpc2varchoices[2],0.);
    TPC2_pisel_pi1->Fill(tpc2varchoices[2],0.);
    TPC2_pisel_p1->Fill(tpc2varchoices[2],0.);
    TPC2_pisel_e1->Fill(tpc2varchoices[2],0.);
    TPC2_psel_mu1->Fill(tpc2varchoices[2],0.);
    TPC2_psel_pi1->Fill(tpc2varchoices[2],0.);
    TPC2_psel_p1->Fill(tpc2varchoices[2],0.);
    TPC2_psel_e1->Fill(tpc2varchoices[2],0.);
    TPC2_esel_mu1->Fill(tpc2varchoices[2],0.);
    TPC2_esel_pi1->Fill(tpc2varchoices[2],0.);
    TPC2_esel_p1->Fill(tpc2varchoices[2],0.);
    TPC2_esel_e1->Fill(tpc2varchoices[2],0.);
  
    TPC2_musel_mu2->Fill(tpc2varchoices[0],0.);
    TPC2_musel_pi2->Fill(tpc2varchoices[0],0.); 
    TPC2_musel_p2->Fill(tpc2varchoices[0],0.);
    TPC2_musel_e2->Fill(tpc2varchoices[0],0.);
    TPC2_pisel_mu2->Fill(tpc2varchoices[0],0.);
    TPC2_pisel_pi2->Fill(tpc2varchoices[0],0.);
    TPC2_pisel_p2->Fill(tpc2varchoices[0],0.);
    TPC2_pisel_e2->Fill(tpc2varchoices[0],0.);
    TPC2_psel_mu2->Fill(tpc2varchoices[0],0.);
    TPC2_psel_pi2->Fill(tpc2varchoices[0],0.);
    TPC2_psel_p2->Fill(tpc2varchoices[0],0.);
    TPC2_psel_e2->Fill(tpc2varchoices[0],0.);
    TPC2_esel_mu2->Fill(tpc2varchoices[0],0.);
    TPC2_esel_pi2->Fill(tpc2varchoices[0],0.);
    TPC2_esel_p2->Fill(tpc2varchoices[0],0.);
    TPC2_esel_e2->Fill(tpc2varchoices[0],0.);
    
    TPC2_musel_mu2->Fill(tpc2varchoices[1],0.);
    TPC2_musel_pi2->Fill(tpc2varchoices[1],0.); 
    TPC2_musel_p2->Fill(tpc2varchoices[1],0.);
    TPC2_musel_e2->Fill(tpc2varchoices[1],0.);
    TPC2_pisel_mu2->Fill(tpc2varchoices[1],0.);
    TPC2_pisel_pi2->Fill(tpc2varchoices[1],0.);
    TPC2_pisel_p2->Fill(tpc2varchoices[1],0.);
    TPC2_pisel_e2->Fill(tpc2varchoices[1],0.);
    TPC2_psel_mu2->Fill(tpc2varchoices[1],0.);
    TPC2_psel_pi2->Fill(tpc2varchoices[1],0.);
    TPC2_psel_p2->Fill(tpc2varchoices[1],0.);
    TPC2_psel_e2->Fill(tpc2varchoices[1],0.);
    TPC2_esel_mu2->Fill(tpc2varchoices[1],0.);
    TPC2_esel_pi2->Fill(tpc2varchoices[1],0.);
    TPC2_esel_p2->Fill(tpc2varchoices[1],0.);
    TPC2_esel_e2->Fill(tpc2varchoices[1],0.);
    
    TPC2_musel_mu2->Fill(tpc2varchoices[2],0.);
    TPC2_musel_pi2->Fill(tpc2varchoices[2],0.); 
    TPC2_musel_p2->Fill(tpc2varchoices[2],0.);
    TPC2_musel_e2->Fill(tpc2varchoices[2],0.);
    TPC2_pisel_mu2->Fill(tpc2varchoices[2],0.);
    TPC2_pisel_pi2->Fill(tpc2varchoices[2],0.);
    TPC2_pisel_p2->Fill(tpc2varchoices[2],0.);
    TPC2_pisel_e2->Fill(tpc2varchoices[2],0.);
    TPC2_psel_mu2->Fill(tpc2varchoices[2],0.);
    TPC2_psel_pi2->Fill(tpc2varchoices[2],0.);
    TPC2_psel_p2->Fill(tpc2varchoices[2],0.);
    TPC2_psel_e2->Fill(tpc2varchoices[2],0.);
    TPC2_esel_mu2->Fill(tpc2varchoices[2],0.);
    TPC2_esel_pi2->Fill(tpc2varchoices[2],0.);
    TPC2_esel_p2->Fill(tpc2varchoices[2],0.);
    TPC2_esel_e2->Fill(tpc2varchoices[2],0.);

    TPC2_musel_mu_diff1->Fill(tpc2varchoices[0], TPC2_musel_mu1->GetBinContent(1)-TPC2_musel_mu1->GetBinContent(1) );
    TPC2_musel_pi_diff1->Fill(tpc2varchoices[0], TPC2_musel_pi1->GetBinContent(1)-TPC2_musel_pi1->GetBinContent(1) ); 
    TPC2_musel_p_diff1->Fill(tpc2varchoices[0], TPC2_musel_p1->GetBinContent(1)-TPC2_musel_p1->GetBinContent(1) );
    TPC2_musel_e_diff1->Fill(tpc2varchoices[0], TPC2_musel_e1->GetBinContent(1)-TPC2_musel_e1->GetBinContent(1) );
    TPC2_pisel_mu_diff1->Fill(tpc2varchoices[0], TPC2_pisel_mu1->GetBinContent(1)-TPC2_pisel_mu1->GetBinContent(1) );
    TPC2_pisel_pi_diff1->Fill(tpc2varchoices[0], TPC2_pisel_pi1->GetBinContent(1)-TPC2_pisel_pi1->GetBinContent(1) );
    TPC2_pisel_p_diff1->Fill(tpc2varchoices[0], TPC2_pisel_p1->GetBinContent(1)-TPC2_pisel_p1->GetBinContent(1) );
    TPC2_pisel_e_diff1->Fill(tpc2varchoices[0], TPC2_pisel_e1->GetBinContent(1)-TPC2_pisel_e1->GetBinContent(1) );
    TPC2_psel_mu_diff1->Fill(tpc2varchoices[0], TPC2_psel_mu1->GetBinContent(1)-TPC2_psel_mu1->GetBinContent(1) );
    TPC2_psel_pi_diff1->Fill(tpc2varchoices[0], TPC2_psel_pi1->GetBinContent(1)-TPC2_psel_pi1->GetBinContent(1) );
    TPC2_psel_p_diff1->Fill(tpc2varchoices[0], TPC2_psel_p1->GetBinContent(1)-TPC2_psel_p1->GetBinContent(1) );
    TPC2_psel_e_diff1->Fill(tpc2varchoices[0], TPC2_psel_e1->GetBinContent(1)-TPC2_psel_e1->GetBinContent(1) );
    TPC2_esel_mu_diff1->Fill(tpc2varchoices[0], TPC2_esel_mu1->GetBinContent(1)-TPC2_esel_mu1->GetBinContent(1) );
    TPC2_esel_pi_diff1->Fill(tpc2varchoices[0], TPC2_esel_pi1->GetBinContent(1)-TPC2_esel_pi1->GetBinContent(1) );
    TPC2_esel_p_diff1->Fill(tpc2varchoices[0], TPC2_esel_p1->GetBinContent(1)-TPC2_esel_p1->GetBinContent(1) );
    TPC2_esel_e_diff1->Fill(tpc2varchoices[0], TPC2_esel_e1->GetBinContent(1)-TPC2_esel_e1->GetBinContent(1) );
    
    TPC2_musel_mu_diff1->Fill(tpc2varchoices[1], TPC2_musel_mu1->GetBinContent(2)-TPC2_musel_mu1->GetBinContent(1) );
    TPC2_musel_pi_diff1->Fill(tpc2varchoices[1], TPC2_musel_pi1->GetBinContent(2)-TPC2_musel_pi1->GetBinContent(1) ); 
    TPC2_musel_p_diff1->Fill(tpc2varchoices[1], TPC2_musel_p1->GetBinContent(2)-TPC2_musel_p1->GetBinContent(1) );
    TPC2_musel_e_diff1->Fill(tpc2varchoices[1], TPC2_musel_e1->GetBinContent(2)-TPC2_musel_e1->GetBinContent(1) );
    TPC2_pisel_mu_diff1->Fill(tpc2varchoices[1], TPC2_pisel_mu1->GetBinContent(2)-TPC2_pisel_mu1->GetBinContent(1) );
    TPC2_pisel_pi_diff1->Fill(tpc2varchoices[1], TPC2_pisel_pi1->GetBinContent(2)-TPC2_pisel_pi1->GetBinContent(1) );
    TPC2_pisel_p_diff1->Fill(tpc2varchoices[1], TPC2_pisel_p1->GetBinContent(2)-TPC2_pisel_p1->GetBinContent(1) );
    TPC2_pisel_e_diff1->Fill(tpc2varchoices[1], TPC2_pisel_e1->GetBinContent(2)-TPC2_pisel_e1->GetBinContent(1) );
    TPC2_psel_mu_diff1->Fill(tpc2varchoices[1], TPC2_psel_mu1->GetBinContent(2)-TPC2_psel_mu1->GetBinContent(1) );
    TPC2_psel_pi_diff1->Fill(tpc2varchoices[1], TPC2_psel_pi1->GetBinContent(2)-TPC2_psel_pi1->GetBinContent(1) );
    TPC2_psel_p_diff1->Fill(tpc2varchoices[1], TPC2_psel_p1->GetBinContent(2)-TPC2_psel_p1->GetBinContent(1) );
    TPC2_psel_e_diff1->Fill(tpc2varchoices[1], TPC2_psel_e1->GetBinContent(2)-TPC2_psel_e1->GetBinContent(1) );
    TPC2_esel_mu_diff1->Fill(tpc2varchoices[1], TPC2_esel_mu1->GetBinContent(2)-TPC2_esel_mu1->GetBinContent(1) );
    TPC2_esel_pi_diff1->Fill(tpc2varchoices[1], TPC2_esel_pi1->GetBinContent(2)-TPC2_esel_pi1->GetBinContent(1) );
    TPC2_esel_p_diff1->Fill(tpc2varchoices[1], TPC2_esel_p1->GetBinContent(2)-TPC2_esel_p1->GetBinContent(1) );
    TPC2_esel_e_diff1->Fill(tpc2varchoices[1], TPC2_esel_e1->GetBinContent(2)-TPC2_esel_e1->GetBinContent(1) );
    
    TPC2_musel_mu_diff1->Fill(tpc2varchoices[2], TPC2_musel_mu1->GetBinContent(3)-TPC2_musel_mu1->GetBinContent(1) );
    TPC2_musel_pi_diff1->Fill(tpc2varchoices[2], TPC2_musel_pi1->GetBinContent(3)-TPC2_musel_pi1->GetBinContent(1) ); 
    TPC2_musel_p_diff1->Fill(tpc2varchoices[2], TPC2_musel_p1->GetBinContent(3)-TPC2_musel_p1->GetBinContent(1) );
    TPC2_musel_e_diff1->Fill(tpc2varchoices[2], TPC2_musel_e1->GetBinContent(3)-TPC2_musel_e1->GetBinContent(1) );
    TPC2_pisel_mu_diff1->Fill(tpc2varchoices[2], TPC2_pisel_mu1->GetBinContent(3)-TPC2_pisel_mu1->GetBinContent(1) );
    TPC2_pisel_pi_diff1->Fill(tpc2varchoices[2], TPC2_pisel_pi1->GetBinContent(3)-TPC2_pisel_pi1->GetBinContent(1) );
    TPC2_pisel_p_diff1->Fill(tpc2varchoices[2], TPC2_pisel_p1->GetBinContent(3)-TPC2_pisel_p1->GetBinContent(1) );
    TPC2_pisel_e_diff1->Fill(tpc2varchoices[2], TPC2_pisel_e1->GetBinContent(3)-TPC2_pisel_e1->GetBinContent(1) );
    TPC2_psel_mu_diff1->Fill(tpc2varchoices[2], TPC2_psel_mu1->GetBinContent(3)-TPC2_psel_mu1->GetBinContent(1) );
    TPC2_psel_pi_diff1->Fill(tpc2varchoices[2], TPC2_psel_pi1->GetBinContent(3)-TPC2_psel_pi1->GetBinContent(1) );
    TPC2_psel_p_diff1->Fill(tpc2varchoices[2], TPC2_psel_p1->GetBinContent(3)-TPC2_psel_p1->GetBinContent(1) );
    TPC2_psel_e_diff1->Fill(tpc2varchoices[2], TPC2_psel_e1->GetBinContent(3)-TPC2_psel_e1->GetBinContent(1) );
    TPC2_esel_mu_diff1->Fill(tpc2varchoices[2], TPC2_esel_mu1->GetBinContent(3)-TPC2_esel_mu1->GetBinContent(1) );
    TPC2_esel_pi_diff1->Fill(tpc2varchoices[2], TPC2_esel_pi1->GetBinContent(3)-TPC2_esel_pi1->GetBinContent(1) );
    TPC2_esel_p_diff1->Fill(tpc2varchoices[2], TPC2_esel_p1->GetBinContent(3)-TPC2_esel_p1->GetBinContent(1) );
    TPC2_esel_e_diff1->Fill(tpc2varchoices[2], TPC2_esel_e1->GetBinContent(3)-TPC2_esel_e1->GetBinContent(1) );
  
    TPC2_musel_mu_diff2->Fill(tpc2varchoices[0], TPC2_musel_mu2->GetBinContent(1)-TPC2_musel_mu2->GetBinContent(1) );
    TPC2_musel_pi_diff2->Fill(tpc2varchoices[0], TPC2_musel_pi2->GetBinContent(1)-TPC2_musel_pi2->GetBinContent(1) ); 
    TPC2_musel_p_diff2->Fill(tpc2varchoices[0], TPC2_musel_p2->GetBinContent(1)-TPC2_musel_p2->GetBinContent(1) );
    TPC2_musel_e_diff2->Fill(tpc2varchoices[0], TPC2_musel_e2->GetBinContent(1)-TPC2_musel_e2->GetBinContent(1) );
    TPC2_pisel_mu_diff2->Fill(tpc2varchoices[0], TPC2_pisel_mu2->GetBinContent(1)-TPC2_pisel_mu2->GetBinContent(1) );
    TPC2_pisel_pi_diff2->Fill(tpc2varchoices[0], TPC2_pisel_pi2->GetBinContent(1)-TPC2_pisel_pi2->GetBinContent(1) );
    TPC2_pisel_p_diff2->Fill(tpc2varchoices[0], TPC2_pisel_p2->GetBinContent(1)-TPC2_pisel_p2->GetBinContent(1) );
    TPC2_pisel_e_diff2->Fill(tpc2varchoices[0], TPC2_pisel_e2->GetBinContent(1)-TPC2_pisel_e2->GetBinContent(1) );
    TPC2_psel_mu_diff2->Fill(tpc2varchoices[0], TPC2_psel_mu2->GetBinContent(1)-TPC2_psel_mu2->GetBinContent(1) );
    TPC2_psel_pi_diff2->Fill(tpc2varchoices[0], TPC2_psel_pi2->GetBinContent(1)-TPC2_psel_pi2->GetBinContent(1) );
    TPC2_psel_p_diff2->Fill(tpc2varchoices[0], TPC2_psel_p2->GetBinContent(1)-TPC2_psel_p2->GetBinContent(1) );
    TPC2_psel_e_diff2->Fill(tpc2varchoices[0], TPC2_psel_e2->GetBinContent(1)-TPC2_psel_e2->GetBinContent(1) );
    TPC2_esel_mu_diff2->Fill(tpc2varchoices[0], TPC2_esel_mu2->GetBinContent(1)-TPC2_esel_mu2->GetBinContent(1) );
    TPC2_esel_pi_diff2->Fill(tpc2varchoices[0], TPC2_esel_pi2->GetBinContent(1)-TPC2_esel_pi2->GetBinContent(1) );
    TPC2_esel_p_diff2->Fill(tpc2varchoices[0], TPC2_esel_p2->GetBinContent(1)-TPC2_esel_p2->GetBinContent(1) );
    TPC2_esel_e_diff2->Fill(tpc2varchoices[0], TPC2_esel_e2->GetBinContent(1)-TPC2_esel_e2->GetBinContent(1) );
    
    TPC2_musel_mu_diff2->Fill(tpc2varchoices[1], TPC2_musel_mu2->GetBinContent(2)-TPC2_musel_mu2->GetBinContent(1) );
    TPC2_musel_pi_diff2->Fill(tpc2varchoices[1], TPC2_musel_pi2->GetBinContent(2)-TPC2_musel_pi2->GetBinContent(1) ); 
    TPC2_musel_p_diff2->Fill(tpc2varchoices[1], TPC2_musel_p2->GetBinContent(2)-TPC2_musel_p2->GetBinContent(1) );
    TPC2_musel_e_diff2->Fill(tpc2varchoices[1], TPC2_musel_e2->GetBinContent(2)-TPC2_musel_e2->GetBinContent(1) );
    TPC2_pisel_mu_diff2->Fill(tpc2varchoices[1], TPC2_pisel_mu2->GetBinContent(2)-TPC2_pisel_mu2->GetBinContent(1) );
    TPC2_pisel_pi_diff2->Fill(tpc2varchoices[1], TPC2_pisel_pi2->GetBinContent(2)-TPC2_pisel_pi2->GetBinContent(1) );
    TPC2_pisel_p_diff2->Fill(tpc2varchoices[1], TPC2_pisel_p2->GetBinContent(2)-TPC2_pisel_p2->GetBinContent(1) );
    TPC2_pisel_e_diff2->Fill(tpc2varchoices[1], TPC2_pisel_e2->GetBinContent(2)-TPC2_pisel_e2->GetBinContent(1) );
    TPC2_psel_mu_diff2->Fill(tpc2varchoices[1], TPC2_psel_mu2->GetBinContent(2)-TPC2_psel_mu2->GetBinContent(1) );
    TPC2_psel_pi_diff2->Fill(tpc2varchoices[1], TPC2_psel_pi2->GetBinContent(2)-TPC2_psel_pi2->GetBinContent(1) );
    TPC2_psel_p_diff2->Fill(tpc2varchoices[1], TPC2_psel_p2->GetBinContent(2)-TPC2_psel_p2->GetBinContent(1) );
    TPC2_psel_e_diff2->Fill(tpc2varchoices[1], TPC2_psel_e2->GetBinContent(2)-TPC2_psel_e2->GetBinContent(1) );
    TPC2_esel_mu_diff2->Fill(tpc2varchoices[1], TPC2_esel_mu2->GetBinContent(2)-TPC2_esel_mu2->GetBinContent(1) );
    TPC2_esel_pi_diff2->Fill(tpc2varchoices[1], TPC2_esel_pi2->GetBinContent(2)-TPC2_esel_pi2->GetBinContent(1) );
    TPC2_esel_p_diff2->Fill(tpc2varchoices[1], TPC2_esel_p2->GetBinContent(2)-TPC2_esel_p2->GetBinContent(1) );
    TPC2_esel_e_diff2->Fill(tpc2varchoices[1], TPC2_esel_e2->GetBinContent(2)-TPC2_esel_e2->GetBinContent(1) );
    
    TPC2_musel_mu_diff2->Fill(tpc2varchoices[2], TPC2_musel_mu2->GetBinContent(3)-TPC2_musel_mu2->GetBinContent(1) );
    TPC2_musel_pi_diff2->Fill(tpc2varchoices[2], TPC2_musel_pi2->GetBinContent(3)-TPC2_musel_pi2->GetBinContent(1) ); 
    TPC2_musel_p_diff2->Fill(tpc2varchoices[2], TPC2_musel_p2->GetBinContent(3)-TPC2_musel_p2->GetBinContent(1) );
    TPC2_musel_e_diff2->Fill(tpc2varchoices[2], TPC2_musel_e2->GetBinContent(3)-TPC2_musel_e2->GetBinContent(1) );
    TPC2_pisel_mu_diff2->Fill(tpc2varchoices[2], TPC2_pisel_mu2->GetBinContent(3)-TPC2_pisel_mu2->GetBinContent(1) );
    TPC2_pisel_pi_diff2->Fill(tpc2varchoices[2], TPC2_pisel_pi2->GetBinContent(3)-TPC2_pisel_pi2->GetBinContent(1) );
    TPC2_pisel_p_diff2->Fill(tpc2varchoices[2], TPC2_pisel_p2->GetBinContent(3)-TPC2_pisel_p2->GetBinContent(1) );
    TPC2_pisel_e_diff2->Fill(tpc2varchoices[2], TPC2_pisel_e2->GetBinContent(3)-TPC2_pisel_e2->GetBinContent(1) );
    TPC2_psel_mu_diff2->Fill(tpc2varchoices[2], TPC2_psel_mu2->GetBinContent(3)-TPC2_psel_mu2->GetBinContent(1) );
    TPC2_psel_pi_diff2->Fill(tpc2varchoices[2], TPC2_psel_pi2->GetBinContent(3)-TPC2_psel_pi2->GetBinContent(1) );
    TPC2_psel_p_diff2->Fill(tpc2varchoices[2], TPC2_psel_p2->GetBinContent(3)-TPC2_psel_p2->GetBinContent(1) );
    TPC2_psel_e_diff2->Fill(tpc2varchoices[2], TPC2_psel_e2->GetBinContent(3)-TPC2_psel_e2->GetBinContent(1) );
    TPC2_esel_mu_diff2->Fill(tpc2varchoices[2], TPC2_esel_mu2->GetBinContent(3)-TPC2_esel_mu2->GetBinContent(1) );
    TPC2_esel_pi_diff2->Fill(tpc2varchoices[2], TPC2_esel_pi2->GetBinContent(3)-TPC2_esel_pi2->GetBinContent(1) );
    TPC2_esel_p_diff2->Fill(tpc2varchoices[2], TPC2_esel_p2->GetBinContent(3)-TPC2_esel_p2->GetBinContent(1) );
    TPC2_esel_e_diff2->Fill(tpc2varchoices[2], TPC2_esel_e2->GetBinContent(3)-TPC2_esel_e2->GetBinContent(1) );
  
    TCanvas* canvas_TPC2_choices_sig_split = new TCanvas("canvas_TPC2_choices_sig_split","",200,10,2000,800);
    canvas_TPC2_choices_sig_split->Divide(2,1,0.005,0.005);
    canvas_TPC2_choices_sig_split->cd(1);
    TPC2_musel_mu_diff1->GetYaxis()->SetRangeUser(0, 1);
    TPC2_musel_mu_diff1->GetXaxis()->SetRangeUser(0, 4);
    TPC2_musel_mu_diff1->GetYaxis()->SetTitle("Difference in efficiency");
    TPC2_musel_mu_diff1->GetYaxis()->SetLabelSize(0.025);
    TPC2_musel_mu_diff1->GetYaxis()->SetTitleSize(0.025);
    TPC2_musel_mu_diff1->GetYaxis()->SetTitleOffset(1.2);
    
    TPC2_musel_mu_diff1->Draw("B");
    TPC2_pisel_pi_diff1->Draw("B same");
    TPC2_psel_p_diff1->Draw("B same");
    TPC2_esel_e_diff1->Draw("B same");
    
    TLegend *legend_sig = new TLegend(0.55,0.65,0.76,0.82);
    legend_sig->AddEntry(TPC2_musel_mu_diff1,"#mu^{+} identified as #mu^{+}","f");
    legend_sig->AddEntry(TPC2_pisel_pi_diff1,"#pi^{+} identified as #pi^{+}","f");
    legend_sig->AddEntry(TPC2_psel_p_diff1,"p identified as p","f");
    legend_sig->AddEntry(TPC2_esel_e_diff1,"e^{+} identified as e^{+}","f");
    legend_sig->Draw();
    
    TCanvas* canvas_TPC2_choices_bkg_split = new TCanvas("canvas_TPC2_choices_bkg_split","",200,10,2000,800);
    canvas_TPC2_choices_bkg_split->Divide(2,1,0.005,0.005);
    canvas_TPC2_choices_bkg_split->cd(1);
    TPC2_pisel_mu_diff1->GetYaxis()->SetRangeUser(0, 0.35);
    TPC2_pisel_mu_diff1->GetXaxis()->SetRangeUser(0, 4);
    TPC2_pisel_mu_diff1->GetYaxis()->SetTitle("Difference in efficiency");
    TPC2_pisel_mu_diff1->GetYaxis()->SetLabelSize(0.025);
    TPC2_pisel_mu_diff1->GetYaxis()->SetTitleSize(0.025);
    TPC2_pisel_mu_diff1->GetYaxis()->SetTitleOffset(1.4);
    
    TPC2_pisel_mu_diff1->Draw("B");
    TPC2_psel_mu_diff1->Draw("B same");
    TPC2_esel_mu_diff1->Draw("B same");
    TPC2_musel_pi_diff1->Draw("B same");
    TPC2_psel_pi_diff1->Draw("B same");
    TPC2_esel_pi_diff1->Draw("B same");
    TPC2_musel_p_diff1->Draw("B same");
    TPC2_pisel_p_diff1->Draw("B same");
    TPC2_esel_p_diff1->Draw("B same");
    TPC2_musel_e_diff1->Draw("B same");
    TPC2_pisel_e_diff1->Draw("B same");
    TPC2_psel_e_diff1->Draw("B same");

    TLegend *legend_bkg = new TLegend(0.55,0.65,0.76,0.82);
    legend_bkg->AddEntry(TPC2_pisel_mu_diff1,"#mu^{+} identified as #pi^{+}","f");
    legend_bkg->AddEntry(TPC2_psel_mu_diff1,"#mu^{+} identified as p","f");
    legend_bkg->AddEntry(TPC2_esel_mu_diff1,"#mu^{+} identified as e^{+}","f");
    legend_bkg->AddEntry(TPC2_musel_pi_diff1,"#pi^{+} identified as #mu^{+}","f");
    legend_bkg->AddEntry(TPC2_psel_pi_diff1,"#pi^{+} identified as p","f");
    legend_bkg->AddEntry(TPC2_esel_pi_diff1,"#pi^{+} identified as e^{+}","f");
    legend_bkg->AddEntry(TPC2_musel_p_diff1,"p identified as #mu^{+}","f");
    legend_bkg->AddEntry(TPC2_pisel_p_diff1,"p identified as #pi^{+}","f");
    legend_bkg->AddEntry(TPC2_esel_p_diff1,"p identified as e^{+}","f");
    legend_bkg->AddEntry(TPC2_musel_e_diff1,"e^{+} identified as #mu^{+}","f");
    legend_bkg->AddEntry(TPC2_pisel_e_diff1,"e^{+} identified as #pi^{+}","f");
    legend_bkg->AddEntry(TPC2_psel_e_diff1,"e^{+} identified as p","f");
    legend_bkg->Draw();
    
    canvas_TPC2_choices_sig_split->cd(2);
    TPC2_musel_mu_diff2->GetYaxis()->SetRangeUser(-0.005, 0.03);
    TPC2_musel_mu_diff2->GetXaxis()->SetRangeUser(1, 3);
    TPC2_musel_mu_diff2->GetYaxis()->SetTitle("Difference in efficiency");
    TPC2_musel_mu_diff2->GetYaxis()->SetLabelSize(0.025);
    TPC2_musel_mu_diff2->GetYaxis()->SetTitleSize(0.025);
    TPC2_musel_mu_diff2->GetYaxis()->SetTitleOffset(1.6);
    
    TPC2_musel_mu_diff2->Draw("B");
    TPC2_pisel_pi_diff2->Draw("B same");
    TPC2_psel_p_diff2->Draw("B same");
    TPC2_esel_e_diff2->Draw("B same");
    
    canvas_TPC2_choices_bkg_split->cd(2);
    TPC2_pisel_mu_diff2->GetYaxis()->SetRangeUser(-0.03, 0.015);
    TPC2_pisel_mu_diff2->GetXaxis()->SetRangeUser(1, 3);
    TPC2_pisel_mu_diff2->GetYaxis()->SetTitle("Difference in efficiency");
    TPC2_pisel_mu_diff2->GetYaxis()->SetLabelSize(0.025);
    TPC2_pisel_mu_diff2->GetYaxis()->SetTitleSize(0.025);
    TPC2_pisel_mu_diff2->GetYaxis()->SetTitleOffset(1.5);
    
    TPC2_pisel_mu_diff2->Draw("B");
    TPC2_psel_mu_diff2->Draw("B same");
    TPC2_esel_mu_diff2->Draw("B same");
    TPC2_musel_pi_diff2->Draw("B same");
    TPC2_psel_pi_diff2->Draw("B same");
    TPC2_esel_pi_diff2->Draw("B same");
    TPC2_musel_p_diff2->Draw("B same");
    TPC2_pisel_p_diff2->Draw("B same");
    TPC2_esel_p_diff2->Draw("B same");
    TPC2_musel_e_diff2->Draw("B same");
    TPC2_pisel_e_diff2->Draw("B same");
    TPC2_psel_e_diff2->Draw("B same");
    
    //canvas_TPC2_choices_bkg_diff->BuildLegend();

}
