{
    gStyle->SetTitleYOffset(1.7);
    gStyle->SetOptStat(0);
    //gStyle->SetLabelSize(0.025);
    //gStyle->SetTitleSize(0.025);
    
    //Float_t refvalue_cc1pi_mu, refvalue_cc1pi_pi, refvalue_pg_mu, refvalue_pg_pi, refvalue_pg_p, refvalue_pg_e;
    
    Float_t bar_width_sig = 0.2;
    Float_t bar_offset_sig = 0.5 - bar_width_sig*2;
    
    Float_t bar_width_bkg = 0.0625;
    Float_t bar_offset_bkg = 0.5 - bar_width_bkg*6;
    
    // =============== TPC2 variable choice ===============
    
    const char *tpc2varchoices[3] = {"TPC2 dE/dx","TPC2 pulls","TPC2 likelihoods"};
    
    TH1F* TPC2_musel_mu1 = new TH1F("TPC2_musel_mu1","#mu^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_pi1 = new TH1F("TPC2_musel_pi1","#pi^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_p1 = new TH1F("TPC2_musel_p1","p identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_e1 = new TH1F("TPC2_musel_e1","e^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_pisel_mu1 = new TH1F("TPC2_pisel_mu1","#mu^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_pi1 = new TH1F("TPC2_pisel_pi1","#pi^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_p1 = new TH1F("TPC2_pisel_p1","p identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_e1 = new TH1F("TPC2_pisel_e1","e^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_psel_mu1 = new TH1F("TPC2_psel_mu1","#mu^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_pi1 = new TH1F("TPC2_psel_pi1","#pi^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_p1 = new TH1F("TPC2_psel_p1","p identified as p",3,0,3);
    TH1F* TPC2_psel_e1 = new TH1F("TPC2_psel_e1","e^{+} identified as p",3,0,3);
    TH1F* TPC2_esel_mu1 = new TH1F("TPC2_esel_mu1","#mu^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_pi1 = new TH1F("TPC2_esel_pi1","#pi^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_p1 = new TH1F("TPC2_esel_p1","p identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_e1 = new TH1F("TPC2_esel_e1","e^{+} identified as e^{+}",3,0,3);
  
    TH1F* TPC2_musel_mu2 = new TH1F("TPC2_musel_mu2","#mu^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_pi2 = new TH1F("TPC2_musel_pi2","#pi^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_p2 = new TH1F("TPC2_musel_p2","p identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_e2 = new TH1F("TPC2_musel_e2","e^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_pisel_mu2 = new TH1F("TPC2_pisel_mu2","#mu^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_pi2 = new TH1F("TPC2_pisel_pi2","#pi^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_p2 = new TH1F("TPC2_pisel_p2","p identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_e2 = new TH1F("TPC2_pisel_e2","e^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_psel_mu2 = new TH1F("TPC2_psel_mu2","#mu^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_pi2 = new TH1F("TPC2_psel_pi2","#pi^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_p2 = new TH1F("TPC2_psel_p2","p identified as p",3,0,3);
    TH1F* TPC2_psel_e2 = new TH1F("TPC2_psel_e2","e^{+} identified as p",3,0,3);
    TH1F* TPC2_esel_mu2 = new TH1F("TPC2_esel_mu2","#mu^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_pi2 = new TH1F("TPC2_esel_pi2","#pi^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_p2 = new TH1F("TPC2_esel_p2","p identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_e2 = new TH1F("TPC2_esel_e2","e^{+} identified as e^{+}",3,0,3);
    
    TH1F* TPC2_musel_mu_diff1 = new TH1F("TPC2_musel_mu_diff1","#mu^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_pi_diff1 = new TH1F("TPC2_musel_pi_diff1","#pi^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_p_diff1 = new TH1F("TPC2_musel_p_diff1","p identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_e_diff1 = new TH1F("TPC2_musel_e_diff1","e^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_pisel_mu_diff1 = new TH1F("TPC2_pisel_mu_diff1","#mu^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_pi_diff1 = new TH1F("TPC2_pisel_pi_diff1","#pi^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_p_diff1 = new TH1F("TPC2_pisel_p_diff1","p identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_e_diff1 = new TH1F("TPC2_pisel_e_diff1","e^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_psel_mu_diff1 = new TH1F("TPC2_psel_mu_diff1","#mu^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_pi_diff1 = new TH1F("TPC2_psel_pi_diff1","#pi^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_p_diff1 = new TH1F("TPC2_psel_p_diff1","p identified as p",3,0,3);
    TH1F* TPC2_psel_e_diff1 = new TH1F("TPC2_psel_e_diff1","e^{+} identified as p",3,0,3);
    TH1F* TPC2_esel_mu_diff1 = new TH1F("TPC2_esel_mu_diff1","#mu^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_pi_diff1 = new TH1F("TPC2_esel_pi_diff1","#pi^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_p_diff1 = new TH1F("TPC2_esel_p_diff1","p identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_e_diff1 = new TH1F("TPC2_esel_e_diff1","e^{+} identified as e^{+}",3,0,3);
  
    TH1F* TPC2_musel_mu_diff2 = new TH1F("TPC2_musel_mu_diff2","#mu^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_pi_diff2 = new TH1F("TPC2_musel_pi_diff2","#pi^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_p_diff2 = new TH1F("TPC2_musel_p_diff2","p identified as #mu^{+}",3,0,3);
    TH1F* TPC2_musel_e_diff2 = new TH1F("TPC2_musel_e_diff2","e^{+} identified as #mu^{+}",3,0,3);
    TH1F* TPC2_pisel_mu_diff2 = new TH1F("TPC2_pisel_mu_diff2","#mu^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_pi_diff2 = new TH1F("TPC2_pisel_pi_diff2","#pi^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_p_diff2 = new TH1F("TPC2_pisel_p_diff2","p identified as #pi^{+}",3,0,3);
    TH1F* TPC2_pisel_e_diff2 = new TH1F("TPC2_pisel_e_diff2","e^{+} identified as #pi^{+}",3,0,3);
    TH1F* TPC2_psel_mu_diff2 = new TH1F("TPC2_psel_mu_diff2","#mu^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_pi_diff2 = new TH1F("TPC2_psel_pi_diff2","#pi^{+} identified as p",3,0,3);
    TH1F* TPC2_psel_p_diff2 = new TH1F("TPC2_psel_p_diff2","p identified as p",3,0,3);
    TH1F* TPC2_psel_e_diff2 = new TH1F("TPC2_psel_e_diff2","e^{+} identified as p",3,0,3);
    TH1F* TPC2_esel_mu_diff2 = new TH1F("TPC2_esel_mu_diff2","#mu^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_pi_diff2 = new TH1F("TPC2_esel_pi_diff2","#pi^{+} identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_p_diff2 = new TH1F("TPC2_esel_p_diff2","p identified as e^{+}",3,0,3);
    TH1F* TPC2_esel_e_diff2 = new TH1F("TPC2_esel_e_diff2","e^{+} identified as e^{+}",3,0,3);
    
    TPC2_musel_mu1->SetFillColor( kBlue);
    TPC2_musel_pi1->SetFillColor( kRed);
    TPC2_musel_p1->SetFillColor( kGreen);
    TPC2_musel_e1->SetFillColor( kMagenta);
    TPC2_pisel_mu1->SetFillColor( kBlue);
    TPC2_pisel_pi1->SetFillColor( kRed); 
    TPC2_pisel_p1->SetFillColor( kGreen+1);
    TPC2_pisel_e1->SetFillColor( kMagenta+1);
    TPC2_psel_mu1->SetFillColor( kBlue+1);
    TPC2_psel_pi1->SetFillColor( kRed+1);
    TPC2_psel_p1->SetFillColor( kGreen); 
    TPC2_psel_e1->SetFillColor( kMagenta+2);
    TPC2_esel_mu1->SetFillColor( kBlue+2);
    TPC2_esel_pi1->SetFillColor( kRed+2);
    TPC2_esel_p1->SetFillColor( kGreen+2);
    TPC2_esel_e1->SetFillColor( kMagenta);
    
    TPC2_musel_mu_diff1->SetFillColor( kBlue);
    TPC2_musel_pi_diff1->SetFillColor( kRed);
    TPC2_musel_p_diff1->SetFillColor( kGreen);
    TPC2_musel_e_diff1->SetFillColor( kMagenta);
    TPC2_pisel_mu_diff1->SetFillColor( kBlue);
    TPC2_pisel_pi_diff1->SetFillColor( kRed);
    TPC2_pisel_p_diff1->SetFillColor( kGreen+1);
    TPC2_pisel_e_diff1->SetFillColor( kMagenta+1);
    TPC2_psel_mu_diff1->SetFillColor( kBlue+1);
    TPC2_psel_pi_diff1->SetFillColor( kRed+1);
    TPC2_psel_p_diff1->SetFillColor( kGreen);
    TPC2_psel_e_diff1->SetFillColor( kMagenta+2);
    TPC2_esel_mu_diff1->SetFillColor( kBlue+2);
    TPC2_esel_pi_diff1->SetFillColor( kRed+2);
    TPC2_esel_p_diff1->SetFillColor( kGreen+2);
    TPC2_esel_e_diff1->SetFillColor( kMagenta);
    
    TPC2_musel_mu1->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); TPC2_musel_mu1->SetBarWidth(bar_width_sig);
    TPC2_pisel_pi1->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); TPC2_pisel_pi1->SetBarWidth(bar_width_sig);
    TPC2_psel_p1->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); TPC2_psel_p1->SetBarWidth(bar_width_sig);
    TPC2_esel_e1->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); TPC2_esel_e1->SetBarWidth(bar_width_sig);
    
    TPC2_musel_mu_diff1->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); TPC2_musel_mu_diff1->SetBarWidth(bar_width_sig);
    TPC2_pisel_pi_diff1->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); TPC2_pisel_pi_diff1->SetBarWidth(bar_width_sig);
    TPC2_psel_p_diff1->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); TPC2_psel_p_diff1->SetBarWidth(bar_width_sig);
    TPC2_esel_e_diff1->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); TPC2_esel_e_diff1->SetBarWidth(bar_width_sig);
    
    TPC2_pisel_mu1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); TPC2_pisel_mu1->SetBarWidth(bar_width_bkg);
    TPC2_psel_mu1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); TPC2_psel_mu1->SetBarWidth(bar_width_bkg);
    TPC2_esel_mu1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); TPC2_esel_mu1->SetBarWidth(bar_width_bkg);
    TPC2_musel_pi1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); TPC2_musel_pi1->SetBarWidth(bar_width_bkg);
    TPC2_psel_pi1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); TPC2_psel_pi1->SetBarWidth(bar_width_bkg);
    TPC2_esel_pi1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); TPC2_esel_pi1->SetBarWidth(bar_width_bkg);
    TPC2_musel_p1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); TPC2_musel_p1->SetBarWidth(bar_width_bkg);
    TPC2_pisel_p1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); TPC2_pisel_p1->SetBarWidth(bar_width_bkg);
    TPC2_esel_p1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); TPC2_esel_p1->SetBarWidth(bar_width_bkg);
    TPC2_musel_e1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); TPC2_musel_e1->SetBarWidth(bar_width_bkg);
    TPC2_pisel_e1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); TPC2_pisel_e1->SetBarWidth(bar_width_bkg);
    TPC2_psel_e1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); TPC2_psel_e1->SetBarWidth(bar_width_bkg);
    
    TPC2_pisel_mu_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); TPC2_pisel_mu_diff1->SetBarWidth(bar_width_bkg);
    TPC2_psel_mu_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); TPC2_psel_mu_diff1->SetBarWidth(bar_width_bkg);
    TPC2_esel_mu_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); TPC2_esel_mu_diff1->SetBarWidth(bar_width_bkg);
    TPC2_musel_pi_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); TPC2_musel_pi_diff1->SetBarWidth(bar_width_bkg);
    TPC2_psel_pi_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); TPC2_psel_pi_diff1->SetBarWidth(bar_width_bkg);
    TPC2_esel_pi_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); TPC2_esel_pi_diff1->SetBarWidth(bar_width_bkg);
    TPC2_musel_p_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); TPC2_musel_p_diff1->SetBarWidth(bar_width_bkg);
    TPC2_pisel_p_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); TPC2_pisel_p_diff1->SetBarWidth(bar_width_bkg);
    TPC2_esel_p_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); TPC2_esel_p_diff1->SetBarWidth(bar_width_bkg);
    TPC2_musel_e_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); TPC2_musel_e_diff1->SetBarWidth(bar_width_bkg);
    TPC2_pisel_e_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); TPC2_pisel_e_diff1->SetBarWidth(bar_width_bkg);
    TPC2_psel_e_diff1->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); TPC2_psel_e_diff1->SetBarWidth(bar_width_bkg);
  
    TPC2_musel_mu2->SetFillColor( kBlue);
    TPC2_musel_pi2->SetFillColor( kRed);
    TPC2_musel_p2->SetFillColor( kGreen);
    TPC2_musel_e2->SetFillColor( kMagenta);
    TPC2_pisel_mu2->SetFillColor( kBlue);
    TPC2_pisel_pi2->SetFillColor( kRed); 
    TPC2_pisel_p2->SetFillColor( kGreen+1);
    TPC2_pisel_e2->SetFillColor( kMagenta+1);
    TPC2_psel_mu2->SetFillColor( kBlue+1);
    TPC2_psel_pi2->SetFillColor( kRed+1);
    TPC2_psel_p2->SetFillColor( kGreen); 
    TPC2_psel_e2->SetFillColor( kMagenta+2);
    TPC2_esel_mu2->SetFillColor( kBlue+2);
    TPC2_esel_pi2->SetFillColor( kRed+2);
    TPC2_esel_p2->SetFillColor( kGreen+2);
    TPC2_esel_e2->SetFillColor( kMagenta);
    
    TPC2_musel_mu_diff2->SetFillColor( kBlue);
    TPC2_musel_pi_diff2->SetFillColor( kRed);
    TPC2_musel_p_diff2->SetFillColor( kGreen);
    TPC2_musel_e_diff2->SetFillColor( kMagenta);
    TPC2_pisel_mu_diff2->SetFillColor( kBlue);
    TPC2_pisel_pi_diff2->SetFillColor( kRed);
    TPC2_pisel_p_diff2->SetFillColor( kGreen+1);
    TPC2_pisel_e_diff2->SetFillColor( kMagenta+1);
    TPC2_psel_mu_diff2->SetFillColor( kBlue+1);
    TPC2_psel_pi_diff2->SetFillColor( kRed+1);
    TPC2_psel_p_diff2->SetFillColor( kGreen);
    TPC2_psel_e_diff2->SetFillColor( kMagenta+2);
    TPC2_esel_mu_diff2->SetFillColor( kBlue+2);
    TPC2_esel_pi_diff2->SetFillColor( kRed+2);
    TPC2_esel_p_diff2->SetFillColor( kGreen+2);
    TPC2_esel_e_diff2->SetFillColor( kMagenta);
    
    TPC2_musel_mu2->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); TPC2_musel_mu2->SetBarWidth(bar_width_sig);
    TPC2_pisel_pi2->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); TPC2_pisel_pi2->SetBarWidth(bar_width_sig);
    TPC2_psel_p2->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); TPC2_psel_p2->SetBarWidth(bar_width_sig);
    TPC2_esel_e2->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); TPC2_esel_e2->SetBarWidth(bar_width_sig);
    
    TPC2_musel_mu_diff2->SetBarOffset(bar_offset_sig + (bar_width_sig*0)); TPC2_musel_mu_diff2->SetBarWidth(bar_width_sig);
    TPC2_pisel_pi_diff2->SetBarOffset(bar_offset_sig + (bar_width_sig*1)); TPC2_pisel_pi_diff2->SetBarWidth(bar_width_sig);
    TPC2_psel_p_diff2->SetBarOffset(bar_offset_sig + (bar_width_sig*2)); TPC2_psel_p_diff2->SetBarWidth(bar_width_sig);
    TPC2_esel_e_diff2->SetBarOffset(bar_offset_sig + (bar_width_sig*3)); TPC2_esel_e_diff2->SetBarWidth(bar_width_sig);
    
    TPC2_pisel_mu2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); TPC2_pisel_mu2->SetBarWidth(bar_width_bkg);
    TPC2_psel_mu2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); TPC2_psel_mu2->SetBarWidth(bar_width_bkg);
    TPC2_esel_mu2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); TPC2_esel_mu2->SetBarWidth(bar_width_bkg);
    TPC2_musel_pi2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); TPC2_musel_pi2->SetBarWidth(bar_width_bkg);
    TPC2_psel_pi2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); TPC2_psel_pi2->SetBarWidth(bar_width_bkg);
    TPC2_esel_pi2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); TPC2_esel_pi2->SetBarWidth(bar_width_bkg);
    TPC2_musel_p2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); TPC2_musel_p2->SetBarWidth(bar_width_bkg);
    TPC2_pisel_p2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); TPC2_pisel_p2->SetBarWidth(bar_width_bkg);
    TPC2_esel_p2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); TPC2_esel_p2->SetBarWidth(bar_width_bkg);
    TPC2_musel_e2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); TPC2_musel_e2->SetBarWidth(bar_width_bkg);
    TPC2_pisel_e2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); TPC2_pisel_e2->SetBarWidth(bar_width_bkg);
    TPC2_psel_e2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); TPC2_psel_e2->SetBarWidth(bar_width_bkg);
    
    TPC2_pisel_mu_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*0)); TPC2_pisel_mu_diff2->SetBarWidth(bar_width_bkg);
    TPC2_psel_mu_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*1)); TPC2_psel_mu_diff2->SetBarWidth(bar_width_bkg);
    TPC2_esel_mu_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*2)); TPC2_esel_mu_diff2->SetBarWidth(bar_width_bkg);
    TPC2_musel_pi_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*3)); TPC2_musel_pi_diff2->SetBarWidth(bar_width_bkg);
    TPC2_psel_pi_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*4)); TPC2_psel_pi_diff2->SetBarWidth(bar_width_bkg);
    TPC2_esel_pi_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*5)); TPC2_esel_pi_diff2->SetBarWidth(bar_width_bkg);
    TPC2_musel_p_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*6)); TPC2_musel_p_diff2->SetBarWidth(bar_width_bkg);
    TPC2_pisel_p_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*7)); TPC2_pisel_p_diff2->SetBarWidth(bar_width_bkg);
    TPC2_esel_p_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*8)); TPC2_esel_p_diff2->SetBarWidth(bar_width_bkg);
    TPC2_musel_e_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*9)); TPC2_musel_e_diff2->SetBarWidth(bar_width_bkg);
    TPC2_pisel_e_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*10)); TPC2_pisel_e_diff2->SetBarWidth(bar_width_bkg);
    TPC2_psel_e_diff2->SetBarOffset(bar_offset_bkg + (bar_width_bkg*11)); TPC2_psel_e_diff2->SetBarWidth(bar_width_bkg);
    
    TPC2_musel_mu1->Fill(tpc2varchoices[0],0.928289);
    TPC2_musel_pi1->Fill(tpc2varchoices[0],0.334697); 
    TPC2_musel_p1->Fill(tpc2varchoices[0],0.0214871);
    TPC2_musel_e1->Fill(tpc2varchoices[0],0.0600211);
    TPC2_pisel_mu1->Fill(tpc2varchoices[0],0.0618413);
    TPC2_pisel_pi1->Fill(tpc2varchoices[0],0.621291);
    TPC2_pisel_p1->Fill(tpc2varchoices[0],0.0515288);
    TPC2_pisel_e1->Fill(tpc2varchoices[0],0.112822);
    TPC2_psel_mu1->Fill(tpc2varchoices[0],0.00942397);
    TPC2_psel_pi1->Fill(tpc2varchoices[0],0.0424109);
    TPC2_psel_p1->Fill(tpc2varchoices[0],0.917126);
    TPC2_psel_e1->Fill(tpc2varchoices[0],0.178731);
    TPC2_esel_mu1->Fill(tpc2varchoices[0],0.000446105);
    TPC2_esel_pi1->Fill(tpc2varchoices[0],0.00160108);
    TPC2_esel_p1->Fill(tpc2varchoices[0],0.00985798);
    TPC2_esel_e1->Fill(tpc2varchoices[0],0.648426);
    
    TPC2_musel_mu1->Fill(tpc2varchoices[1],0.930101);
    TPC2_musel_pi1->Fill(tpc2varchoices[1],0.322138); 
    TPC2_musel_p1->Fill(tpc2varchoices[1],0.0215205);
    TPC2_musel_e1->Fill(tpc2varchoices[1],0.0456123);
    TPC2_pisel_mu1->Fill(tpc2varchoices[1],0.0625105);
    TPC2_pisel_pi1->Fill(tpc2varchoices[1],0.648082);
    TPC2_pisel_p1->Fill(tpc2varchoices[1],0.0403342);
    TPC2_pisel_e1->Fill(tpc2varchoices[1],0.107059);
    TPC2_psel_mu1->Fill(tpc2varchoices[1],0.00708192);
    TPC2_psel_pi1->Fill(tpc2varchoices[1],0.0286416);
    TPC2_psel_p1->Fill(tpc2varchoices[1],0.926951);
    TPC2_psel_e1->Fill(tpc2varchoices[1],0.169528);
    TPC2_esel_mu1->Fill(tpc2varchoices[1],0.000306697);
    TPC2_esel_pi1->Fill(tpc2varchoices[1],0.00113855);
    TPC2_esel_p1->Fill(tpc2varchoices[1],0.0111947);
    TPC2_esel_e1->Fill(tpc2varchoices[1],0.677801);
    
    TPC2_musel_mu1->Fill(tpc2varchoices[2],0.929292);
    TPC2_musel_pi1->Fill(tpc2varchoices[2],0.323739); 
    TPC2_musel_p1->Fill(tpc2varchoices[2],0.0220217);
    TPC2_musel_e1->Fill(tpc2varchoices[2],0.0336515);
    TPC2_pisel_mu1->Fill(tpc2varchoices[2],0.0629844);
    TPC2_pisel_pi1->Fill(tpc2varchoices[2],0.639543);
    TPC2_pisel_p1->Fill(tpc2varchoices[2],0.0580117);
    TPC2_pisel_e1->Fill(tpc2varchoices[2],0.107338);
    TPC2_psel_mu1->Fill(tpc2varchoices[2],0.00741649);
    TPC2_psel_pi1->Fill(tpc2varchoices[2],0.0338718);
    TPC2_psel_p1->Fill(tpc2varchoices[2],0.911211);
    TPC2_psel_e1->Fill(tpc2varchoices[2],0.189173);
    TPC2_esel_mu1->Fill(tpc2varchoices[2],0.000306697);
    TPC2_esel_pi1->Fill(tpc2varchoices[2],0.00284637);
    TPC2_esel_p1->Fill(tpc2varchoices[2],0.00875522);
    TPC2_esel_e1->Fill(tpc2varchoices[2],0.669838);
  
    TPC2_musel_mu2->Fill(tpc2varchoices[0],0.930167);
    TPC2_musel_pi2->Fill(tpc2varchoices[0],0.334224); 
    TPC2_musel_p2->Fill(tpc2varchoices[0],0.0219532);
    TPC2_musel_e2->Fill(tpc2varchoices[0],0.0587263);
    TPC2_pisel_mu2->Fill(tpc2varchoices[0],0.0609076);
    TPC2_pisel_pi2->Fill(tpc2varchoices[0],0.624843);
    TPC2_pisel_p2->Fill(tpc2varchoices[0],0.0514271);
    TPC2_pisel_e2->Fill(tpc2varchoices[0],0.117053);
    TPC2_psel_mu2->Fill(tpc2varchoices[0],0.00850294);
    TPC2_psel_pi2->Fill(tpc2varchoices[0],0.0394815);
    TPC2_psel_p2->Fill(tpc2varchoices[0],0.915088);
    TPC2_psel_e2->Fill(tpc2varchoices[0],0.179742);
    TPC2_esel_mu2->Fill(tpc2varchoices[0],0.000422132);
    TPC2_esel_pi2->Fill(tpc2varchoices[0],0.00145128);
    TPC2_esel_p2->Fill(tpc2varchoices[0],0.0115317);
    TPC2_esel_e2->Fill(tpc2varchoices[0],0.644478);
    
    TPC2_musel_mu2->Fill(tpc2varchoices[1],0.930107);
    TPC2_musel_pi2->Fill(tpc2varchoices[1],0.321129); 
    TPC2_musel_p2->Fill(tpc2varchoices[1],0.0208072);
    TPC2_musel_e2->Fill(tpc2varchoices[1],0.0439877);
    TPC2_pisel_mu2->Fill(tpc2varchoices[1],0.062566);
    TPC2_pisel_pi2->Fill(tpc2varchoices[1],0.650966);
    TPC2_pisel_p2->Fill(tpc2varchoices[1],0.044372);
    TPC2_pisel_e2->Fill(tpc2varchoices[1],0.109157);
    TPC2_psel_mu2->Fill(tpc2varchoices[1],0.00702548);
    TPC2_psel_pi2->Fill(tpc2varchoices[1],0.026321);
    TPC2_psel_p2->Fill(tpc2varchoices[1],0.922752);
    TPC2_psel_e2->Fill(tpc2varchoices[1],0.171304);
    TPC2_esel_mu2->Fill(tpc2varchoices[1],0.000301523);
    TPC2_esel_pi2->Fill(tpc2varchoices[1],0.00158322);
    TPC2_esel_p2->Fill(tpc2varchoices[1],0.0120689);
    TPC2_esel_e2->Fill(tpc2varchoices[1],0.675552);
    
    TPC2_musel_mu2->Fill(tpc2varchoices[2],0.927815);
    TPC2_musel_pi2->Fill(tpc2varchoices[2],0.322647); 
    TPC2_musel_p2->Fill(tpc2varchoices[2],0.0224904);
    TPC2_musel_e2->Fill(tpc2varchoices[2],0.0320429);
    TPC2_pisel_mu2->Fill(tpc2varchoices[2],0.063953);
    TPC2_pisel_pi2->Fill(tpc2varchoices[2],0.64249);
    TPC2_pisel_p2->Fill(tpc2varchoices[2],0.05662);
    TPC2_pisel_e2->Fill(tpc2varchoices[2],0.111951);
    TPC2_psel_mu2->Fill(tpc2varchoices[2],0.00799035);
    TPC2_psel_pi2->Fill(tpc2varchoices[2],0.032357);
    TPC2_psel_p2->Fill(tpc2varchoices[2],0.910719);
    TPC2_psel_e2->Fill(tpc2varchoices[2],0.18952);
    TPC2_esel_mu2->Fill(tpc2varchoices[2],0.000241218);
    TPC2_esel_pi2->Fill(tpc2varchoices[2],0.00250676);
    TPC2_esel_p2->Fill(tpc2varchoices[2],0.0101708);
    TPC2_esel_e2->Fill(tpc2varchoices[2],0.666486);

    TPC2_musel_mu_diff1->Fill(tpc2varchoices[0], TPC2_musel_mu1->GetBinContent(1)-TPC2_musel_mu1->GetBinContent(1) );
    TPC2_musel_pi_diff1->Fill(tpc2varchoices[0], TPC2_musel_pi1->GetBinContent(1)-TPC2_musel_pi1->GetBinContent(1) ); 
    TPC2_musel_p_diff1->Fill(tpc2varchoices[0], TPC2_musel_p1->GetBinContent(1)-TPC2_musel_p1->GetBinContent(1) );
    TPC2_musel_e_diff1->Fill(tpc2varchoices[0], TPC2_musel_e1->GetBinContent(1)-TPC2_musel_e1->GetBinContent(1) );
    TPC2_pisel_mu_diff1->Fill(tpc2varchoices[0], TPC2_pisel_mu1->GetBinContent(1)-TPC2_pisel_mu1->GetBinContent(1) );
    TPC2_pisel_pi_diff1->Fill(tpc2varchoices[0], TPC2_pisel_pi1->GetBinContent(1)-TPC2_pisel_pi1->GetBinContent(1) );
    TPC2_pisel_p_diff1->Fill(tpc2varchoices[0], TPC2_pisel_p1->GetBinContent(1)-TPC2_pisel_p1->GetBinContent(1) );
    TPC2_pisel_e_diff1->Fill(tpc2varchoices[0], TPC2_pisel_e1->GetBinContent(1)-TPC2_pisel_e1->GetBinContent(1) );
    TPC2_psel_mu_diff1->Fill(tpc2varchoices[0], TPC2_psel_mu1->GetBinContent(1)-TPC2_psel_mu1->GetBinContent(1) );
    TPC2_psel_pi_diff1->Fill(tpc2varchoices[0], TPC2_psel_pi1->GetBinContent(1)-TPC2_psel_pi1->GetBinContent(1) );
    TPC2_psel_p_diff1->Fill(tpc2varchoices[0], TPC2_psel_p1->GetBinContent(1)-TPC2_psel_p1->GetBinContent(1) );
    TPC2_psel_e_diff1->Fill(tpc2varchoices[0], TPC2_psel_e1->GetBinContent(1)-TPC2_psel_e1->GetBinContent(1) );
    TPC2_esel_mu_diff1->Fill(tpc2varchoices[0], TPC2_esel_mu1->GetBinContent(1)-TPC2_esel_mu1->GetBinContent(1) );
    TPC2_esel_pi_diff1->Fill(tpc2varchoices[0], TPC2_esel_pi1->GetBinContent(1)-TPC2_esel_pi1->GetBinContent(1) );
    TPC2_esel_p_diff1->Fill(tpc2varchoices[0], TPC2_esel_p1->GetBinContent(1)-TPC2_esel_p1->GetBinContent(1) );
    TPC2_esel_e_diff1->Fill(tpc2varchoices[0], TPC2_esel_e1->GetBinContent(1)-TPC2_esel_e1->GetBinContent(1) );
    
    TPC2_musel_mu_diff1->Fill(tpc2varchoices[1], TPC2_musel_mu1->GetBinContent(2)-TPC2_musel_mu1->GetBinContent(1) );
    TPC2_musel_pi_diff1->Fill(tpc2varchoices[1], TPC2_musel_pi1->GetBinContent(2)-TPC2_musel_pi1->GetBinContent(1) ); 
    TPC2_musel_p_diff1->Fill(tpc2varchoices[1], TPC2_musel_p1->GetBinContent(2)-TPC2_musel_p1->GetBinContent(1) );
    TPC2_musel_e_diff1->Fill(tpc2varchoices[1], TPC2_musel_e1->GetBinContent(2)-TPC2_musel_e1->GetBinContent(1) );
    TPC2_pisel_mu_diff1->Fill(tpc2varchoices[1], TPC2_pisel_mu1->GetBinContent(2)-TPC2_pisel_mu1->GetBinContent(1) );
    TPC2_pisel_pi_diff1->Fill(tpc2varchoices[1], TPC2_pisel_pi1->GetBinContent(2)-TPC2_pisel_pi1->GetBinContent(1) );
    TPC2_pisel_p_diff1->Fill(tpc2varchoices[1], TPC2_pisel_p1->GetBinContent(2)-TPC2_pisel_p1->GetBinContent(1) );
    TPC2_pisel_e_diff1->Fill(tpc2varchoices[1], TPC2_pisel_e1->GetBinContent(2)-TPC2_pisel_e1->GetBinContent(1) );
    TPC2_psel_mu_diff1->Fill(tpc2varchoices[1], TPC2_psel_mu1->GetBinContent(2)-TPC2_psel_mu1->GetBinContent(1) );
    TPC2_psel_pi_diff1->Fill(tpc2varchoices[1], TPC2_psel_pi1->GetBinContent(2)-TPC2_psel_pi1->GetBinContent(1) );
    TPC2_psel_p_diff1->Fill(tpc2varchoices[1], TPC2_psel_p1->GetBinContent(2)-TPC2_psel_p1->GetBinContent(1) );
    TPC2_psel_e_diff1->Fill(tpc2varchoices[1], TPC2_psel_e1->GetBinContent(2)-TPC2_psel_e1->GetBinContent(1) );
    TPC2_esel_mu_diff1->Fill(tpc2varchoices[1], TPC2_esel_mu1->GetBinContent(2)-TPC2_esel_mu1->GetBinContent(1) );
    TPC2_esel_pi_diff1->Fill(tpc2varchoices[1], TPC2_esel_pi1->GetBinContent(2)-TPC2_esel_pi1->GetBinContent(1) );
    TPC2_esel_p_diff1->Fill(tpc2varchoices[1], TPC2_esel_p1->GetBinContent(2)-TPC2_esel_p1->GetBinContent(1) );
    TPC2_esel_e_diff1->Fill(tpc2varchoices[1], TPC2_esel_e1->GetBinContent(2)-TPC2_esel_e1->GetBinContent(1) );
    
    TPC2_musel_mu_diff1->Fill(tpc2varchoices[2], TPC2_musel_mu1->GetBinContent(3)-TPC2_musel_mu1->GetBinContent(1) );
    TPC2_musel_pi_diff1->Fill(tpc2varchoices[2], TPC2_musel_pi1->GetBinContent(3)-TPC2_musel_pi1->GetBinContent(1) ); 
    TPC2_musel_p_diff1->Fill(tpc2varchoices[2], TPC2_musel_p1->GetBinContent(3)-TPC2_musel_p1->GetBinContent(1) );
    TPC2_musel_e_diff1->Fill(tpc2varchoices[2], TPC2_musel_e1->GetBinContent(3)-TPC2_musel_e1->GetBinContent(1) );
    TPC2_pisel_mu_diff1->Fill(tpc2varchoices[2], TPC2_pisel_mu1->GetBinContent(3)-TPC2_pisel_mu1->GetBinContent(1) );
    TPC2_pisel_pi_diff1->Fill(tpc2varchoices[2], TPC2_pisel_pi1->GetBinContent(3)-TPC2_pisel_pi1->GetBinContent(1) );
    TPC2_pisel_p_diff1->Fill(tpc2varchoices[2], TPC2_pisel_p1->GetBinContent(3)-TPC2_pisel_p1->GetBinContent(1) );
    TPC2_pisel_e_diff1->Fill(tpc2varchoices[2], TPC2_pisel_e1->GetBinContent(3)-TPC2_pisel_e1->GetBinContent(1) );
    TPC2_psel_mu_diff1->Fill(tpc2varchoices[2], TPC2_psel_mu1->GetBinContent(3)-TPC2_psel_mu1->GetBinContent(1) );
    TPC2_psel_pi_diff1->Fill(tpc2varchoices[2], TPC2_psel_pi1->GetBinContent(3)-TPC2_psel_pi1->GetBinContent(1) );
    TPC2_psel_p_diff1->Fill(tpc2varchoices[2], TPC2_psel_p1->GetBinContent(3)-TPC2_psel_p1->GetBinContent(1) );
    TPC2_psel_e_diff1->Fill(tpc2varchoices[2], TPC2_psel_e1->GetBinContent(3)-TPC2_psel_e1->GetBinContent(1) );
    TPC2_esel_mu_diff1->Fill(tpc2varchoices[2], TPC2_esel_mu1->GetBinContent(3)-TPC2_esel_mu1->GetBinContent(1) );
    TPC2_esel_pi_diff1->Fill(tpc2varchoices[2], TPC2_esel_pi1->GetBinContent(3)-TPC2_esel_pi1->GetBinContent(1) );
    TPC2_esel_p_diff1->Fill(tpc2varchoices[2], TPC2_esel_p1->GetBinContent(3)-TPC2_esel_p1->GetBinContent(1) );
    TPC2_esel_e_diff1->Fill(tpc2varchoices[2], TPC2_esel_e1->GetBinContent(3)-TPC2_esel_e1->GetBinContent(1) );
  
    TPC2_musel_mu_diff2->Fill(tpc2varchoices[0], TPC2_musel_mu2->GetBinContent(1)-TPC2_musel_mu2->GetBinContent(1) );
    TPC2_musel_pi_diff2->Fill(tpc2varchoices[0], TPC2_musel_pi2->GetBinContent(1)-TPC2_musel_pi2->GetBinContent(1) ); 
    TPC2_musel_p_diff2->Fill(tpc2varchoices[0], TPC2_musel_p2->GetBinContent(1)-TPC2_musel_p2->GetBinContent(1) );
    TPC2_musel_e_diff2->Fill(tpc2varchoices[0], TPC2_musel_e2->GetBinContent(1)-TPC2_musel_e2->GetBinContent(1) );
    TPC2_pisel_mu_diff2->Fill(tpc2varchoices[0], TPC2_pisel_mu2->GetBinContent(1)-TPC2_pisel_mu2->GetBinContent(1) );
    TPC2_pisel_pi_diff2->Fill(tpc2varchoices[0], TPC2_pisel_pi2->GetBinContent(1)-TPC2_pisel_pi2->GetBinContent(1) );
    TPC2_pisel_p_diff2->Fill(tpc2varchoices[0], TPC2_pisel_p2->GetBinContent(1)-TPC2_pisel_p2->GetBinContent(1) );
    TPC2_pisel_e_diff2->Fill(tpc2varchoices[0], TPC2_pisel_e2->GetBinContent(1)-TPC2_pisel_e2->GetBinContent(1) );
    TPC2_psel_mu_diff2->Fill(tpc2varchoices[0], TPC2_psel_mu2->GetBinContent(1)-TPC2_psel_mu2->GetBinContent(1) );
    TPC2_psel_pi_diff2->Fill(tpc2varchoices[0], TPC2_psel_pi2->GetBinContent(1)-TPC2_psel_pi2->GetBinContent(1) );
    TPC2_psel_p_diff2->Fill(tpc2varchoices[0], TPC2_psel_p2->GetBinContent(1)-TPC2_psel_p2->GetBinContent(1) );
    TPC2_psel_e_diff2->Fill(tpc2varchoices[0], TPC2_psel_e2->GetBinContent(1)-TPC2_psel_e2->GetBinContent(1) );
    TPC2_esel_mu_diff2->Fill(tpc2varchoices[0], TPC2_esel_mu2->GetBinContent(1)-TPC2_esel_mu2->GetBinContent(1) );
    TPC2_esel_pi_diff2->Fill(tpc2varchoices[0], TPC2_esel_pi2->GetBinContent(1)-TPC2_esel_pi2->GetBinContent(1) );
    TPC2_esel_p_diff2->Fill(tpc2varchoices[0], TPC2_esel_p2->GetBinContent(1)-TPC2_esel_p2->GetBinContent(1) );
    TPC2_esel_e_diff2->Fill(tpc2varchoices[0], TPC2_esel_e2->GetBinContent(1)-TPC2_esel_e2->GetBinContent(1) );
    
    TPC2_musel_mu_diff2->Fill(tpc2varchoices[1], TPC2_musel_mu2->GetBinContent(2)-TPC2_musel_mu2->GetBinContent(1) );
    TPC2_musel_pi_diff2->Fill(tpc2varchoices[1], TPC2_musel_pi2->GetBinContent(2)-TPC2_musel_pi2->GetBinContent(1) ); 
    TPC2_musel_p_diff2->Fill(tpc2varchoices[1], TPC2_musel_p2->GetBinContent(2)-TPC2_musel_p2->GetBinContent(1) );
    TPC2_musel_e_diff2->Fill(tpc2varchoices[1], TPC2_musel_e2->GetBinContent(2)-TPC2_musel_e2->GetBinContent(1) );
    TPC2_pisel_mu_diff2->Fill(tpc2varchoices[1], TPC2_pisel_mu2->GetBinContent(2)-TPC2_pisel_mu2->GetBinContent(1) );
    TPC2_pisel_pi_diff2->Fill(tpc2varchoices[1], TPC2_pisel_pi2->GetBinContent(2)-TPC2_pisel_pi2->GetBinContent(1) );
    TPC2_pisel_p_diff2->Fill(tpc2varchoices[1], TPC2_pisel_p2->GetBinContent(2)-TPC2_pisel_p2->GetBinContent(1) );
    TPC2_pisel_e_diff2->Fill(tpc2varchoices[1], TPC2_pisel_e2->GetBinContent(2)-TPC2_pisel_e2->GetBinContent(1) );
    TPC2_psel_mu_diff2->Fill(tpc2varchoices[1], TPC2_psel_mu2->GetBinContent(2)-TPC2_psel_mu2->GetBinContent(1) );
    TPC2_psel_pi_diff2->Fill(tpc2varchoices[1], TPC2_psel_pi2->GetBinContent(2)-TPC2_psel_pi2->GetBinContent(1) );
    TPC2_psel_p_diff2->Fill(tpc2varchoices[1], TPC2_psel_p2->GetBinContent(2)-TPC2_psel_p2->GetBinContent(1) );
    TPC2_psel_e_diff2->Fill(tpc2varchoices[1], TPC2_psel_e2->GetBinContent(2)-TPC2_psel_e2->GetBinContent(1) );
    TPC2_esel_mu_diff2->Fill(tpc2varchoices[1], TPC2_esel_mu2->GetBinContent(2)-TPC2_esel_mu2->GetBinContent(1) );
    TPC2_esel_pi_diff2->Fill(tpc2varchoices[1], TPC2_esel_pi2->GetBinContent(2)-TPC2_esel_pi2->GetBinContent(1) );
    TPC2_esel_p_diff2->Fill(tpc2varchoices[1], TPC2_esel_p2->GetBinContent(2)-TPC2_esel_p2->GetBinContent(1) );
    TPC2_esel_e_diff2->Fill(tpc2varchoices[1], TPC2_esel_e2->GetBinContent(2)-TPC2_esel_e2->GetBinContent(1) );
    
    TPC2_musel_mu_diff2->Fill(tpc2varchoices[2], TPC2_musel_mu2->GetBinContent(3)-TPC2_musel_mu2->GetBinContent(1) );
    TPC2_musel_pi_diff2->Fill(tpc2varchoices[2], TPC2_musel_pi2->GetBinContent(3)-TPC2_musel_pi2->GetBinContent(1) ); 
    TPC2_musel_p_diff2->Fill(tpc2varchoices[2], TPC2_musel_p2->GetBinContent(3)-TPC2_musel_p2->GetBinContent(1) );
    TPC2_musel_e_diff2->Fill(tpc2varchoices[2], TPC2_musel_e2->GetBinContent(3)-TPC2_musel_e2->GetBinContent(1) );
    TPC2_pisel_mu_diff2->Fill(tpc2varchoices[2], TPC2_pisel_mu2->GetBinContent(3)-TPC2_pisel_mu2->GetBinContent(1) );
    TPC2_pisel_pi_diff2->Fill(tpc2varchoices[2], TPC2_pisel_pi2->GetBinContent(3)-TPC2_pisel_pi2->GetBinContent(1) );
    TPC2_pisel_p_diff2->Fill(tpc2varchoices[2], TPC2_pisel_p2->GetBinContent(3)-TPC2_pisel_p2->GetBinContent(1) );
    TPC2_pisel_e_diff2->Fill(tpc2varchoices[2], TPC2_pisel_e2->GetBinContent(3)-TPC2_pisel_e2->GetBinContent(1) );
    TPC2_psel_mu_diff2->Fill(tpc2varchoices[2], TPC2_psel_mu2->GetBinContent(3)-TPC2_psel_mu2->GetBinContent(1) );
    TPC2_psel_pi_diff2->Fill(tpc2varchoices[2], TPC2_psel_pi2->GetBinContent(3)-TPC2_psel_pi2->GetBinContent(1) );
    TPC2_psel_p_diff2->Fill(tpc2varchoices[2], TPC2_psel_p2->GetBinContent(3)-TPC2_psel_p2->GetBinContent(1) );
    TPC2_psel_e_diff2->Fill(tpc2varchoices[2], TPC2_psel_e2->GetBinContent(3)-TPC2_psel_e2->GetBinContent(1) );
    TPC2_esel_mu_diff2->Fill(tpc2varchoices[2], TPC2_esel_mu2->GetBinContent(3)-TPC2_esel_mu2->GetBinContent(1) );
    TPC2_esel_pi_diff2->Fill(tpc2varchoices[2], TPC2_esel_pi2->GetBinContent(3)-TPC2_esel_pi2->GetBinContent(1) );
    TPC2_esel_p_diff2->Fill(tpc2varchoices[2], TPC2_esel_p2->GetBinContent(3)-TPC2_esel_p2->GetBinContent(1) );
    TPC2_esel_e_diff2->Fill(tpc2varchoices[2], TPC2_esel_e2->GetBinContent(3)-TPC2_esel_e2->GetBinContent(1) );
  
    TCanvas* canvas_TPC2_choices_sig_split = new TCanvas("canvas_TPC2_choices_sig_split","",200,10,2000,800);
    canvas_TPC2_choices_sig_split->Divide(2,1,0.005,0.005);
    canvas_TPC2_choices_sig_split->cd(1);
    TPC2_musel_mu_diff1->GetYaxis()->SetRangeUser(-0.05, 0.05);
    TPC2_musel_mu_diff1->GetXaxis()->SetRangeUser(1, 3);
    TPC2_musel_mu_diff1->GetYaxis()->SetTitle("Difference in efficiency");
    TPC2_musel_mu_diff1->GetYaxis()->SetLabelSize(0.025);
    TPC2_musel_mu_diff1->GetYaxis()->SetTitleSize(0.025);
    TPC2_musel_mu_diff1->GetYaxis()->SetTitleOffset(1.2);
    
    TPC2_musel_mu_diff1->Draw("B");
    TPC2_pisel_pi_diff1->Draw("B same");
    TPC2_psel_p_diff1->Draw("B same");
    TPC2_esel_e_diff1->Draw("B same");
    
    TLegend *legend_sig = new TLegend(0.55,0.65,0.76,0.82);
    legend_sig->AddEntry(TPC2_musel_mu_diff1,"#mu^{+} identified as #mu^{+}","f");
    legend_sig->AddEntry(TPC2_pisel_pi_diff1,"#pi^{+} identified as #pi^{+}","f");
    legend_sig->AddEntry(TPC2_psel_p_diff1,"p identified as p","f");
    legend_sig->AddEntry(TPC2_esel_e_diff1,"e^{+} identified as e^{+}","f");
    legend_sig->Draw();
    
    TCanvas* canvas_TPC2_choices_bkg_split = new TCanvas("canvas_TPC2_choices_bkg_split","",200,10,2000,800);
    canvas_TPC2_choices_bkg_split->Divide(2,1,0.005,0.005);
    canvas_TPC2_choices_bkg_split->cd(1);
    TPC2_pisel_mu_diff1->GetYaxis()->SetRangeUser(-0.05, 0.05);
    TPC2_pisel_mu_diff1->GetXaxis()->SetRangeUser(1, 3);
    TPC2_pisel_mu_diff1->GetYaxis()->SetTitle("Difference in efficiency");
    TPC2_pisel_mu_diff1->GetYaxis()->SetLabelSize(0.025);
    TPC2_pisel_mu_diff1->GetYaxis()->SetTitleSize(0.025);
    TPC2_pisel_mu_diff1->GetYaxis()->SetTitleOffset(1.4);
    
    TPC2_pisel_mu_diff1->Draw("B");
    TPC2_psel_mu_diff1->Draw("B same");
    TPC2_esel_mu_diff1->Draw("B same");
    TPC2_musel_pi_diff1->Draw("B same");
    TPC2_psel_pi_diff1->Draw("B same");
    TPC2_esel_pi_diff1->Draw("B same");
    TPC2_musel_p_diff1->Draw("B same");
    TPC2_pisel_p_diff1->Draw("B same");
    TPC2_esel_p_diff1->Draw("B same");
    TPC2_musel_e_diff1->Draw("B same");
    TPC2_pisel_e_diff1->Draw("B same");
    TPC2_psel_e_diff1->Draw("B same");

    TLegend *legend_bkg = new TLegend(0.55,0.65,0.76,0.82);
    legend_bkg->AddEntry(TPC2_pisel_mu_diff1,"#mu^{+} identified as #pi^{+}","f");
    legend_bkg->AddEntry(TPC2_psel_mu_diff1,"#mu^{+} identified as p","f");
    legend_bkg->AddEntry(TPC2_esel_mu_diff1,"#mu^{+} identified as e^{+}","f");
    legend_bkg->AddEntry(TPC2_musel_pi_diff1,"#pi^{+} identified as #mu^{+}","f");
    legend_bkg->AddEntry(TPC2_psel_pi_diff1,"#pi^{+} identified as p","f");
    legend_bkg->AddEntry(TPC2_esel_pi_diff1,"#pi^{+} identified as e^{+}","f");
    legend_bkg->AddEntry(TPC2_musel_p_diff1,"p identified as #mu^{+}","f");
    legend_bkg->AddEntry(TPC2_pisel_p_diff1,"p identified as #pi^{+}","f");
    legend_bkg->AddEntry(TPC2_esel_p_diff1,"p identified as e^{+}","f");
    legend_bkg->AddEntry(TPC2_musel_e_diff1,"e^{+} identified as #mu^{+}","f");
    legend_bkg->AddEntry(TPC2_pisel_e_diff1,"e^{+} identified as #pi^{+}","f");
    legend_bkg->AddEntry(TPC2_psel_e_diff1,"e^{+} identified as p","f");
    legend_bkg->Draw();
    
    canvas_TPC2_choices_sig_split->cd(2);
    TPC2_musel_mu_diff2->GetYaxis()->SetRangeUser(-0.05, 0.05);
    TPC2_musel_mu_diff2->GetXaxis()->SetRangeUser(1, 3);
    TPC2_musel_mu_diff2->GetYaxis()->SetTitle("Difference in efficiency");
    TPC2_musel_mu_diff2->GetYaxis()->SetLabelSize(0.025);
    TPC2_musel_mu_diff2->GetYaxis()->SetTitleSize(0.025);
    TPC2_musel_mu_diff2->GetYaxis()->SetTitleOffset(1.6);
    
    TPC2_musel_mu_diff2->Draw("B");
    TPC2_pisel_pi_diff2->Draw("B same");
    TPC2_psel_p_diff2->Draw("B same");
    TPC2_esel_e_diff2->Draw("B same");
    
    canvas_TPC2_choices_bkg_split->cd(2);
    TPC2_pisel_mu_diff2->GetYaxis()->SetRangeUser(-0.05, 0.05);
    TPC2_pisel_mu_diff2->GetXaxis()->SetRangeUser(1, 3);
    TPC2_pisel_mu_diff2->GetYaxis()->SetTitle("Difference in efficiency");
    TPC2_pisel_mu_diff2->GetYaxis()->SetLabelSize(0.025);
    TPC2_pisel_mu_diff2->GetYaxis()->SetTitleSize(0.025);
    TPC2_pisel_mu_diff2->GetYaxis()->SetTitleOffset(1.5);
    
    TPC2_pisel_mu_diff2->Draw("B");
    TPC2_psel_mu_diff2->Draw("B same");
    TPC2_esel_mu_diff2->Draw("B same");
    TPC2_musel_pi_diff2->Draw("B same");
    TPC2_psel_pi_diff2->Draw("B same");
    TPC2_esel_pi_diff2->Draw("B same");
    TPC2_musel_p_diff2->Draw("B same");
    TPC2_pisel_p_diff2->Draw("B same");
    TPC2_esel_p_diff2->Draw("B same");
    TPC2_musel_e_diff2->Draw("B same");
    TPC2_pisel_e_diff2->Draw("B same");
    TPC2_psel_e_diff2->Draw("B same");
    
    //canvas_TPC2_choices_bkg_diff->BuildLegend();

}
