# Script to clean up unnecessary (i.e. non-oaAnalysis) files in particle gun output directories. Needs to be run from the particle gun working directory.

rm antimu/output/*cali_*
rm antimu/output/*g4mc_*
rm antimu/output/*elmc_*
rm antimu/output/*logf_*
rm antimu/output/*reco_*
rm antimu/output/*slurm*
rm antimu/output/*catalogue*
rm piplus/output/*cali_*
rm piplus/output/*g4mc_*
rm piplus/output/*elmc_*
rm piplus/output/*logf_*
rm piplus/output/*reco_*
rm piplus/output/*slurm*
rm piplus/output/*catalogue*
rm proton/output/*cali_*
rm proton/output/*g4mc_*
rm proton/output/*elmc_*
rm proton/output/*logf_*
rm proton/output/*reco_*
rm proton/output/*slurm*
rm proton/output/*catalogue*
rm positron/output/*cali_*
rm positron/output/*g4mc_*
rm positron/output/*elmc_*
rm positron/output/*logf_*
rm positron/output/*reco_*
rm positron/output/*slurm*
rm positron/output/*catalogue*
rm mu/output/*cali_*
rm mu/output/*g4mc_*
rm mu/output/*elmc_*
rm mu/output/*logf_*
rm mu/output/*reco_*
rm mu/output/*slurm*
rm mu/output/*catalogue*
rm piminus/output/*cali_*
rm piminus/output/*g4mc_*
rm piminus/output/*elmc_*
rm piminus/output/*logf_*
rm piminus/output/*reco_*
rm piminus/output/*slurm*
rm piminus/output/*catalogue*
rm electron/output/*cali_*
rm electron/output/*g4mc_*
rm electron/output/*elmc_*
rm electron/output/*logf_*
rm electron/output/*reco_*
rm electron/output/*slurm*
rm electron/output/*catalogue*
