source scripts/batch/existing_selection/run5/submit_batch_jobs_run5.sh
source scripts/batch/existing_selection/run6/submit_batch_jobs_run6.sh
source scripts/batch/existing_selection/run7/submit_batch_jobs_run7.sh
source scripts/batch/existing_selection/run9/submit_batch_jobs_run9.sh
